"use client";
import type { ReactNode } from "react";
import Link from "next/link";
import { useParams,useRouter,useSearchParams } from "next/navigation";
import { useEffect,useMemo,useState } from "react";
import { ApiError,Character,SceneSetup,SceneSetupAction,createSceneSetup,getOutline,getSceneSetup,listStoryCharacters,addSceneProp,removeSceneProp,saveSceneActions,saveSceneCharacters,saveSceneDialogue,updateSceneBackground } from "../../../../lib/api";

const ACTIONS:SceneSetupAction["action"][]=["IDLE","TALK","WALK","RUN","WAVE","SIT","JUMP"];
type Line={speakerType:"CHARACTER"|"NARRATOR";characterId:string|null;text:string};
type Act={characterId:string;action:SceneSetupAction["action"]};
const avatar=(c:string)=>({CHILD:"🧒",ADULT:"🧑",ANIMAL:"🐾",FANTASY:"✨",OBJECT:"🧸",OTHER:"⭐"}[c]??"⭐");
const move=<T,>(xs:T[],i:number,d:number)=>{const j=i+d;if(j<0||j>=xs.length)return xs;const a=[...xs],[x]=a.splice(i,1);a.splice(j,0,x);return a};

export default function SceneSetupPage(){
 const {storyId}=useParams<{storyId:string}>(),qs=useSearchParams(),router=useRouter(),requested=qs.get("scene");
 const [outline,setOutline]=useState<Awaited<ReturnType<typeof getOutline>>|null>(null),[setup,setSetup]=useState<SceneSetup|null>(null),[chars,setChars]=useState<Character[]>([]),[sceneId,setSceneId]=useState(""),[selected,setSelected]=useState<string[]>([]),[background,setBackground]=useState<string|null>(null),[dialogue,setDialogue]=useState<Line[]>([]),[acts,setActs]=useState<Act[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[dirty,setDirty]=useState(false),[error,setError]=useState<string|null>(null),[notice,setNotice]=useState<string|null>(null);
 const scenes=outline?.scenes??[],idx=scenes.findIndex(s=>s.id===sceneId),scene=idx>=0?scenes[idx]:scenes[0],charMap=useMemo(()=>new Map(chars.map(c=>[c.id,c])),[chars]);
 async function load(){setLoading(true);setError(null);try{const o=await getOutline(storyId);const id=requested||o.scenes[0]?.id;if(!id)throw new Error("This Story has no Outline Scene yet.");const [c,s]=await Promise.all([listStoryCharacters(storyId),getOrCreate(storyId,id)]);setOutline(o);setSceneId(id);setChars(c);setSetup(s);setSelected(s.characters.sort((a,b)=>a.orderIndex-b.orderIndex).map(x=>x.id));setBackground(s.backgroundPresetKey);setDialogue(s.dialogue.sort((a,b)=>a.sequenceIndex-b.sequenceIndex).map(x=>({speakerType:x.speakerType,characterId:x.characterId,text:x.text})));setActs(s.actions.sort((a,b)=>a.sequenceIndex-b.sequenceIndex).map(x=>({characterId:x.characterId,action:x.action})));setDirty(false)}catch(e){setError(e instanceof ApiError?e.message:e instanceof Error?e.message:"We couldn't load Scene Setup.")}finally{setLoading(false)}}
 async function getOrCreate(s:string,id:string){try{return await getSceneSetup(s,id)}catch(e){if(e instanceof ApiError&&e.status===404)return createSceneSetup(s,id);throw e}}
 useEffect(()=>{const t=setTimeout(()=>void load(),0);return()=>clearTimeout(t)},[storyId,requested]);
 const edit=<T,>(setter:(v:T)=>void,v:T)=>{setter(v);setDirty(true);setNotice(null)};
 async function save(){if(!setup||!scene||saving)return;if(dialogue.some(x=>!x.text.trim()||x.text.trim().length>2000)){setNotice("Dialogue text is required and limited to 2000 characters.");return}if(dialogue.some(x=>x.speakerType==="CHARACTER"&&(!x.characterId||!selected.includes(x.characterId)))){setNotice("Character dialogue must use a selected Story Character.");return}if(dialogue.some(x=>x.speakerType==="NARRATOR"&&x.characterId)){setNotice("Narrator lines cannot reference a Character.");return}if(acts.some(x=>!selected.includes(x.characterId))){setNotice("Actions must reference selected Story Characters.");return}setSaving(true);setNotice(null);try{let s=await updateSceneBackground(storyId,scene.id,background);s=await saveSceneCharacters(storyId,scene.id,selected);s=await saveSceneDialogue(storyId,scene.id,dialogue);s=await saveSceneActions(storyId,scene.id,acts);setSetup(s);setDirty(false);setNotice("Saved")}catch(e){setNotice(e instanceof ApiError?e.message:"Save failed. Try again.")}finally{setSaving(false)}}
 async function addProp(key:string){try{setSetup(await addSceneProp(storyId,sceneId,key));setNotice("Prop added")}catch(e){setNotice(e instanceof ApiError?e.message:"Couldn't add prop")}}
 async function delProp(id:string){try{setSetup(await removeSceneProp(storyId,sceneId,id))}catch(e){setNotice(e instanceof ApiError?e.message:"Couldn't remove prop")}}
 if(loading)return <main className="min-h-screen bg-slate-50 p-8"><div className="mx-auto max-w-6xl rounded-2xl bg-white p-8">Loading Scene Setup…</div></main>;
 if(error||!setup||!scene)return <main className="min-h-screen bg-slate-50 p-8"><div className="mx-auto max-w-3xl rounded-2xl bg-white p-8"><p role="alert" className="text-red-700">{error??"Scene Setup is unavailable."}</p><Link className="mt-5 inline-block underline" href={`/stories/${storyId}/outline`}>Back to Story Outline</Link></div></main>;
 const prev=idx>0?scenes[idx-1]:null,next=idx>=0&&idx<scenes.length-1?scenes[idx+1]:null;
 return <main className="min-h-screen bg-slate-50 text-slate-950"><div className="mx-auto max-w-6xl px-6 py-8"><div className="flex flex-wrap justify-between gap-3"><Link href={`/stories/${storyId}/characters`} className="text-sm text-slate-500">← Characters</Link><div className="flex gap-2"><Link href={`/stories/${storyId}/outline`} className="rounded-lg border bg-white px-3 py-2 text-sm">Outline</Link><button onClick={save} disabled={saving||!dirty} className="rounded-lg bg-slate-950 px-4 py-2 text-sm font-semibold text-white disabled:opacity-40">{saving?"Saving…":dirty?"Save Changes":"Saved"}</button><Link href={`/stories/${storyId}/editor?scene=${scene.id}`} className="rounded-lg bg-indigo-600 px-4 py-2 text-sm font-semibold text-white">Open Editor →</Link></div></div>
 <header className="mt-6 rounded-2xl bg-white p-6 shadow-sm"><div className="flex flex-wrap justify-between gap-5"><div><p className="text-xs font-bold tracking-widest text-indigo-600">SCENE SETUP · SCENE {scene.orderIndex}</p><h1 className="mt-2 text-3xl font-bold">{scene.title}</h1><p className="mt-2 max-w-3xl text-slate-600">{scene.summary}</p><p className="mt-3 text-sm font-semibold">Planned duration: {scene.durationSeconds}s <span className="font-normal text-slate-400">· read-only from Outline</span></p></div><div className="flex gap-2"><button disabled={!prev} onClick={()=>router.push(`/stories/${storyId}/scene-setup?scene=${prev?.id}`)} className="rounded-lg border px-3 py-2 text-sm disabled:opacity-30">← Previous</button><button disabled={!next} onClick={()=>router.push(`/stories/${storyId}/scene-setup?scene=${next?.id}`)} className="rounded-lg border px-3 py-2 text-sm disabled:opacity-30">Next →</button></div></div>{notice&&<div role="status" className="mt-4 rounded-lg border border-indigo-100 bg-indigo-50 p-3 text-sm text-indigo-700">{notice}</div>}</header>
 <div className="mt-6 grid gap-6 lg:grid-cols-2">
 <Section title="1. Background" hint="Controlled preset library. No AI generation."><div className="grid grid-cols-2 gap-3">{setup.backgroundOptions.map(p=><button key={p.key} onClick={()=>edit(setBackground,p.key)} className={`rounded-xl border p-3 text-left ${background===p.key?"border-indigo-500 bg-indigo-50":"bg-white"}`}><div className="flex h-20 items-center justify-center rounded-lg bg-slate-100 text-3xl">🖼️</div><b className="mt-2 block">{p.name}</b><span className="text-xs text-slate-500">{p.category}</span></button>)}</div><button disabled={!background} onClick={()=>edit(setBackground,null)} className="mt-3 text-sm text-red-600 underline disabled:opacity-30">Remove background</button></Section>
 <Section title="2. Characters" hint="Only Characters attached to this Story can be selected. One instance per scene."><div className="space-y-2">{chars.map(c=>{const on=selected.includes(c.id);return <button key={c.id} onClick={()=>edit(setSelected,on?selected.filter(x=>x!==c.id):[...selected,c.id])} className={`flex w-full items-center gap-3 rounded-xl border p-3 text-left ${on?"border-indigo-500 bg-indigo-50":"bg-white"}`}><span className="flex h-10 w-10 items-center justify-center rounded-lg bg-slate-100 text-xl">{avatar(c.category)}</span><span className="flex-1"><b>{c.name}</b><span className="ml-2 text-xs text-slate-500">{c.roleDescription}</span></span><span className="text-xs font-semibold">{on?"Selected":"Add"}</span></button>})}</div>{!chars.length&&<p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-500">No Story Characters. Add them from Characters first.</p>}</Section>
 <Section title="3. Props & Objects" hint="Scene-local preset instances. Repeated presets are allowed."><div className="flex flex-wrap gap-2">{setup.propOptions.map(p=><button key={p.key} onClick={()=>addProp(p.key)} className="rounded-lg border bg-white px-3 py-2 text-sm">+ {p.name}</button>)}</div><div className="mt-4 space-y-2">{setup.props.map(p=><div key={p.id} className="flex justify-between rounded-xl border bg-white p-3"><span><b>{setup.propOptions.find(x=>x.key===p.propPresetKey)?.name??p.propPresetKey}</b><span className="ml-2 text-xs text-slate-400">Instance {p.orderIndex}</span></span><button onClick={()=>delProp(p.id)} className="text-sm text-red-600">Remove</button></div>)}{!setup.props.length&&<p className="text-sm text-slate-500">No props selected.</p>}</div></Section>
 <Section title="4. Dialogue" hint="Manual text only. Voice and timing belong to the future Editor/Timeline."><button onClick={()=>edit(setDialogue,[...dialogue,{speakerType:"NARRATOR",characterId:null,text:""}])} className="rounded-lg border px-3 py-2 text-sm font-semibold">+ Add line</button><div className="mt-3 space-y-3">{dialogue.map((d,i)=><div key={i} className="rounded-xl border bg-white p-3"><div className="flex gap-2"><select value={d.speakerType} onChange={e=>edit(setDialogue,dialogue.map((x,j)=>j===i?{...x,speakerType:e.target.value as Line["speakerType"],characterId:e.target.value==="NARRATOR"?null:x.characterId}:x))} className="rounded-lg border p-2 text-sm"><option value="NARRATOR">Narrator</option><option value="CHARACTER">Character</option></select>{d.speakerType==="CHARACTER"&&<select value={d.characterId??""} onChange={e=>edit(setDialogue,dialogue.map((x,j)=>j===i?{...x,characterId:e.target.value||null}:x))} className="flex-1 rounded-lg border p-2 text-sm"><option value="">Select Character</option>{selected.map(id=><option key={id} value={id}>{charMap.get(id)?.name??"Character"}</option>)}</select>}<button aria-label={`Delete dialogue ${i+1}`} onClick={()=>edit(setDialogue,dialogue.filter((_,j)=>j!==i))} className="px-2 text-red-600">×</button></div><textarea aria-label={`Dialogue ${i+1}`} value={d.text} onChange={e=>edit(setDialogue,dialogue.map((x,j)=>j===i?{...x,text:e.target.value}:x))} rows={2} placeholder="Dialogue text…" className="mt-2 w-full rounded-lg border p-2 text-sm"/><div className="mt-2 flex gap-2"><button disabled={i===0} onClick={()=>edit(setDialogue,move(dialogue,i,-1))} className="text-xs underline disabled:opacity-30">Move up</button><button disabled={i===dialogue.length-1} onClick={()=>edit(setDialogue,move(dialogue,i,1))} className="text-xs underline disabled:opacity-30">Move down</button></div></div>)}{!dialogue.length&&<p className="text-sm text-slate-500">No dialogue yet.</p>}</div></Section>
 <Section title="5. Actions" hint="Preset action intent only. No timing or animation engine."><button onClick={()=>selected[0]?edit(setActs,[...acts,{characterId:selected[0],action:"IDLE"}]):setNotice("Select a Character before adding an action.")} className="rounded-lg border px-3 py-2 text-sm font-semibold">+ Add action</button><div className="mt-3 space-y-2">{acts.map((a,i)=><div key={i} className="flex gap-2 rounded-xl border bg-white p-3"><select value={a.characterId} onChange={e=>edit(setActs,acts.map((x,j)=>j===i?{...x,characterId:e.target.value}:x))} className="flex-1 rounded-lg border p-2 text-sm">{selected.map(id=><option key={id} value={id}>{charMap.get(id)?.name??"Character"}</option>)}</select><select value={a.action} onChange={e=>edit(setActs,acts.map((x,j)=>j===i?{...x,action:e.target.value as Act["action"]}:x))} className="rounded-lg border p-2 text-sm">{ACTIONS.map(x=><option key={x}>{x}</option>)}</select><button disabled={i===0} onClick={()=>edit(setActs,move(acts,i,-1))} className="text-xs underline disabled:opacity-30">↑</button><button disabled={i===acts.length-1} onClick={()=>edit(setActs,move(acts,i,1))} className="text-xs underline disabled:opacity-30">↓</button><button onClick={()=>edit(setActs,acts.filter((_,j)=>j!==i))} className="px-2 text-red-600">×</button></div>)}{!acts.length&&<p className="text-sm text-slate-500">No action intents yet.</p>}</div></Section>
 </div></div></main>;
}
function Section({title,hint,children}:{title:string;hint:string;children:ReactNode}){return <section className="rounded-2xl bg-white p-5 shadow-sm"><h2 className="text-lg font-bold">{title}</h2><p className="mb-4 mt-1 text-xs text-slate-500">{hint}</p>{children}</section>}
