package com.storysprout.api.editor;
import static org.junit.jupiter.api.Assertions.*; import static org.mockito.Mockito.*;
import com.fasterxml.jackson.databind.ObjectMapper; import com.storysprout.api.character.Character; import com.storysprout.api.character.CharacterRepository; import com.storysprout.api.outline.OutlineScene; import com.storysprout.api.outline.OutlineSceneRepository; import com.storysprout.api.scene.SceneSetup; import com.storysprout.api.scene.SceneSetupCharacter; import com.storysprout.api.scene.SceneSetupProp; import com.storysprout.api.scene.SceneSetupRepository; import com.storysprout.api.story.Story; import com.storysprout.api.story.StoryRepository; import java.time.Instant; import java.util.*; import org.junit.jupiter.api.BeforeEach; import org.junit.jupiter.api.Test;
class EditorServiceTest {
 private final StoryRepository stories=mock(StoryRepository.class); private final OutlineSceneRepository outlines=mock(OutlineSceneRepository.class); private final SceneSetupRepository setups=mock(SceneSetupRepository.class); private final CharacterRepository characters=mock(CharacterRepository.class); private final CompositionRepository compositions=mock(CompositionRepository.class); private final EditorService service=new EditorService(stories,outlines,setups,characters,compositions,new ObjectMapper()); private final UUID storyId=UUID.randomUUID(),sceneId=UUID.randomUUID(),characterId=UUID.randomUUID(),projectId=UUID.randomUUID(); private Story story; private OutlineScene scene; private SceneSetup setup; private Character character;
 @BeforeEach void context(){story=mock(Story.class);scene=mock(OutlineScene.class);setup=mock(SceneSetup.class);character=mock(Character.class);when(story.projectId()).thenReturn(projectId);when(story.id()).thenReturn(storyId);when(story.title()).thenReturn("Story");when(scene.id()).thenReturn(sceneId);when(scene.storyId()).thenReturn(storyId);when(scene.title()).thenReturn("Scene");when(scene.summary()).thenReturn("summary");when(scene.durationSeconds()).thenReturn(60);when(scene.orderIndex()).thenReturn(1);when(setup.outlineSceneId()).thenReturn(sceneId);when(setup.backgroundPresetKey()).thenReturn(null);when(setup.characters()).thenReturn(List.of(new SceneSetupCharacter(characterId,1)));when(setup.props()).thenReturn(List.of(new SceneSetupProp(UUID.randomUUID(),"ball",1)));when(setup.dialogue()).thenReturn(List.of());when(setup.actions()).thenReturn(List.of());when(character.id()).thenReturn(characterId);when(character.projectId()).thenReturn(projectId);when(character.name()).thenReturn("Milo");when(stories.findById(storyId)).thenReturn(Optional.of(story));when(outlines.findByIdAndStoryId(sceneId,storyId)).thenReturn(Optional.of(scene));when(setups.findByOutlineSceneId(sceneId)).thenReturn(Optional.of(setup));when(characters.findByStoryId(storyId)).thenReturn(List.of(character));}
 @Test void initializesOnceWithExplicitTypes(){when(compositions.find(projectId,sceneId)).thenReturn(Optional.empty());var created=new Composition(UUID.randomUUID(),projectId,sceneId,new ObjectMapper().createObjectNode(),1,Instant.now(),Instant.now());when(compositions.insert(any(),eq(projectId),eq(sceneId),any())).thenReturn(created);var result=service.open(storyId,sceneId);assertEquals(created,result.composition());var json=org.mockito.ArgumentCaptor.forClass(com.fasterxml.jackson.databind.JsonNode.class);verify(compositions).insert(any(),eq(projectId),eq(sceneId),json.capture());assertEquals("1.1",json.getValue().get("schemaVersion").asText());assertEquals(projectId.toString(),json.getValue().get("projectId").asText());assertEquals("CHARACTER",json.getValue().at("/scenes/0/objects/0/objectType").asText());assertEquals("PROP",json.getValue().at("/scenes/0/objects/1/objectType").asText());assertTrue(json.getValue().at("/scenes/0/timeline").isEmpty());}
 @Test void existingCompositionIsNotRebuilt(){var json=new ObjectMapper().createObjectNode().put("schemaVersion","1.1");var existing=new Composition(UUID.randomUUID(),projectId,sceneId,json,2,Instant.now(),Instant.now());when(compositions.find(projectId,sceneId)).thenReturn(Optional.of(existing));assertSame(existing,service.open(storyId,sceneId).composition());verify(compositions,never()).insert(any(),any(),any(),any());}
 @Test void staleSaveDoesNotOverwrite(){var json=new ObjectMapper().createObjectNode();json.put("schemaVersion","1.1");json.put("projectId",projectId.toString());json.put("width",1920);json.put("height",1080);json.put("fps",30);json.put("durationMs",60000);var sceneJson=json.putArray("scenes").addObject();sceneJson.put("id",sceneId.toString());sceneJson.put("name","Scene");sceneJson.put("durationMs",60000);sceneJson.putArray("objects");sceneJson.putArray("timeline");var current=new Composition(UUID.randomUUID(),projectId,sceneId,json,2,Instant.now(),Instant.now());when(compositions.find(projectId,sceneId)).thenReturn(Optional.of(current));assertThrows(EditorConflictException.class,()->service.save(storyId,sceneId,1,json));verify(compositions,never()).update(any(),any(),any(),anyLong(),any());}
}
