import { describe, expect, it, vi, beforeEach } from "vitest";
import { render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import CreateStoryPage from "../app/create/page";
import StorySetupPage from "../app/create/setup/page";
import { ApiError } from "../lib/api";
import * as api from "../lib/api";

vi.mock("../lib/api", async () => { const actual = await vi.importActual<typeof import("../lib/api")>("../lib/api"); return { ...actual, createProject: vi.fn(), createStory: vi.fn(), listProjects: vi.fn() }; });
let mode = "BLANK";
vi.mock("next/navigation", () => ({ useRouter: () => ({ push: vi.fn(), replace: vi.fn() }), useSearchParams: () => new URLSearchParams(`projectId=p1&mode=${mode}`) }));
beforeEach(() => { vi.clearAllMocks(); mode = "BLANK"; });
const blankStory = { id: "s1", projectId: "p1", title: "Untitled Story", idea: "A rabbit learns to share.", targetAge: "6_8" as const, durationMinutes: 3 as const, visualStyle: "2D" as const, language: "ENGLISH" as const, creationMode: "BLANK" as const, generationStatus: "NOT_REQUESTED" as const, draftContent: null, createdAt: "2026-09-16T10:00:00Z", updatedAt: "2026-09-16T10:00:00Z", continuationPath: "/dashboard" };
async function fillValidSetup(user: ReturnType<typeof userEvent.setup>) { await user.type(screen.getByLabelText("Story idea"), "A rabbit learns to share."); await user.click(screen.getByRole("button", { name: "Ages 6–8" })); }

describe("Story Creation UI", () => {
  it("shows empty dashboard and Create Story", async () => { vi.mocked(api.listProjects).mockResolvedValue([]); const Dashboard = (await import("../app/page")).default; render(<Dashboard />); expect(await screen.findByText("No stories yet")).toBeInTheDocument(); expect(screen.getAllByRole("link", { name: "Create Story" })).toHaveLength(2); });
  it("renders project cards", async () => { vi.mocked(api.listProjects).mockResolvedValue([{ id: "p1", name: "Rabbit Adventure", status: "DRAFT", updatedAt: "2026-09-16T10:00:00Z", createdAt: "2026-09-16T09:00:00Z" }]); const Dashboard = (await import("../app/page")).default; render(<Dashboard />); expect(await screen.findByText("Rabbit Adventure")).toBeInTheDocument(); expect(screen.getByText("DRAFT")).toBeInTheDocument(); });
  it("keeps AI and Blank mutually exclusive and starts setup", async () => { vi.mocked(api.createProject).mockResolvedValue({ id: "p1", name: "Untitled Story", status: "DRAFT", updatedAt: "2026-09-16T10:00:00Z", createdAt: "2026-09-16T10:00:00Z" }); const user = userEvent.setup(); render(<CreateStoryPage />); const ai = screen.getByRole("button", { name: /Start with AI/i }); const blank = screen.getByRole("button", { name: /Blank Story/i }); await user.click(ai); await user.click(blank); expect(blank).toHaveAttribute("aria-pressed", "true"); expect(ai).toHaveAttribute("aria-pressed", "false"); await user.click(screen.getByRole("button", { name: "Continue" })); expect(api.createProject).toHaveBeenCalledTimes(1); });
  it("renders only approved ages and validates incomplete setup", async () => { const user = userEvent.setup(); render(<StorySetupPage />); expect(screen.getByRole("button", { name: "Ages 3–5" })).toBeInTheDocument(); expect(screen.getByRole("button", { name: "Ages 6–8" })).toBeInTheDocument(); expect(screen.getByRole("button", { name: "Ages 9–12" })).toBeInTheDocument(); expect(screen.queryByRole("button", { name: /13/ })).not.toBeInTheDocument(); await user.click(screen.getByRole("button", { name: "Continue" })); expect(screen.getByText("Enter a story idea.")).toBeInTheDocument(); });
  it("selects duration, visual style, and language accessibly", async () => { const user = userEvent.setup(); render(<StorySetupPage />); const duration = screen.getByRole("button", { name: "5 min" }); const style = screen.getByRole("button", { name: "3D" }); const language = screen.getByRole("button", { name: "Hindi" }); await user.click(duration); await user.click(style); await user.click(language); expect(duration).toHaveAttribute("aria-pressed", "true"); expect(style).toHaveAttribute("aria-pressed", "true"); expect(language).toHaveAttribute("aria-pressed", "true"); expect(screen.getByRole("button", { name: "3 min" })).toHaveAttribute("aria-pressed", "false"); });
  it("saves blank story with the selected setup", async () => { vi.mocked(api.createStory).mockResolvedValue(blankStory); const user = userEvent.setup(); render(<StorySetupPage />); await fillValidSetup(user); await user.click(screen.getByRole("button", { name: "5 min" })); await user.click(screen.getByRole("button", { name: "Hybrid" })); await user.click(screen.getByRole("button", { name: "Hindi" })); await user.click(screen.getByRole("button", { name: "Continue" })); expect(api.createStory).toHaveBeenCalledTimes(1); expect(api.createStory).toHaveBeenCalledWith("p1", expect.objectContaining({ creationMode: "BLANK", targetAge: "6_8", durationMinutes: 5, visualStyle: "HYBRID", language: "HINDI" })); });
  it("shows AI generating and success states", async () => { mode = "AI"; vi.mocked(api.createStory).mockResolvedValue({ ...blankStory, creationMode: "AI", generationStatus: "COMPLETED", draftContent: "A rabbit shares a carrot." }); const user = userEvent.setup(); render(<StorySetupPage />); await fillValidSetup(user); await user.click(screen.getByRole("button", { name: "Generate Story" })); expect(await screen.findByText("Your first draft is ready.")).toBeInTheDocument(); });
  it("shows AI failure, preserves setup, and offers retry", async () => { mode = "AI"; vi.mocked(api.createStory).mockRejectedValue(new ApiError(422, "GENERATION_FAILED", "Story generation failed. Your setup was saved.")); const user = userEvent.setup(); render(<StorySetupPage />); await fillValidSetup(user); await user.click(screen.getByRole("button", { name: "Generate Story" })); expect(await screen.findByText(/Story generation failed/)).toBeInTheDocument(); expect(screen.getByLabelText("Story idea")).toHaveValue("A rabbit learns to share."); expect(screen.getByRole("button", { name: "Retry generation" })).toBeEnabled(); });
  it("keeps the primary action disabled while submitting", async () => { let resolve: (value: typeof blankStory) => void = () => {}; vi.mocked(api.createStory).mockImplementation(() => new Promise((r) => { resolve = r; })); const user = userEvent.setup(); render(<StorySetupPage />); await fillValidSetup(user); const submit = screen.getByRole("button", { name: "Continue" }); await user.click(submit); expect(submit).toBeDisabled(); expect(screen.getByText("Saving your story…")).toBeInTheDocument(); resolve(blankStory); });
  it("supports keyboard selection for setup choices", async () => { const user = userEvent.setup(); render(<StorySetupPage />); const age = screen.getByRole("button", { name: "Ages 9–12" }); age.focus(); await user.keyboard("{Enter}"); expect(age).toHaveAttribute("aria-pressed", "true"); });
});