export type Project = { id: string; name: string; status: "DRAFT" | "READY"; createdAt: string; updatedAt: string };
export type Story = { id: string; projectId: string; title: string; idea: string; targetAge: "3_5" | "6_8" | "9_12"; durationMinutes: 1 | 3 | 5; visualStyle: "2D" | "3D" | "HYBRID"; language: "ENGLISH" | "HINDI"; creationMode: "AI" | "BLANK"; generationStatus: "NOT_REQUESTED" | "GENERATING" | "COMPLETED" | "FAILED"; draftContent: string | null; createdAt: string; updatedAt: string; continuationPath: string };
export type OutlineScene = { id: string; storyId: string; orderIndex: number; title: string; summary: string; durationSeconds: number; createdAt: string; updatedAt: string };
export type StoryOutline = { story: Story; scenes: OutlineScene[]; targetDurationSeconds: number; plannedDurationSeconds: number; varianceSeconds: number };
export type CharacterCategory = "CHILD" | "ADULT" | "ANIMAL" | "FANTASY" | "OBJECT" | "OTHER";
export type Character = { id: string; projectId: string; name: string; roleDescription: string; category: CharacterCategory; visualDescription: string; personality: string | null; createdAt: string; updatedAt: string };
export type CharacterSuggestion = Omit<Character, "id" | "projectId" | "createdAt" | "updatedAt">;
export type SceneSetupCharacter = { characterId: string; orderIndex: number };
export type SceneSetupProp = { id: string; propPresetKey: string; orderIndex: number };
export type SceneSetupDialogue = { id: string; sequenceIndex: number; speakerType: "CHARACTER" | "NARRATOR"; characterId: string | null; text: string };
export type SceneSetupAction = { id: string; characterId: string; sequenceIndex: number; action: "IDLE" | "TALK" | "WALK" | "RUN" | "WAVE" | "SIT" | "JUMP" };
export type Preset = { key: string; name: string; category: string };
export type SceneSetup = { id: string; storyId: string; outlineSceneId: string; storyTitle: string; sceneOrder: number; sceneTitle: string; sceneSummary: string; plannedDurationSeconds: number; backgroundPresetKey: string | null; characters: { id: string; name: string; category: string; orderIndex: number }[]; props: SceneSetupProp[]; dialogue: SceneSetupDialogue[]; actions: SceneSetupAction[]; backgroundOptions: Preset[]; propOptions: Preset[] };

type ApiEnvelope<T> = { data: T };
export class ApiError extends Error { constructor(public status: number, public code: string, message: string, public fields: { field: string; message: string }[] = []) { super(message); } }
async function request<T>(path: string, init?: RequestInit): Promise<T> { const response = await fetch(`/api/v1${path}`, { ...init, headers: { "Content-Type": "application/json", ...(init?.headers ?? {}) } }); const body = await response.json().catch(() => ({})); if (!response.ok) { const error = body.error; throw new ApiError(response.status,error?.code ?? "REQUEST_FAILED",error?.message ?? "Request failed",error?.fields ?? []); } return (body as ApiEnvelope<T>).data; }
export const listProjects=()=>request<Project[]>("/projects");
export const listStories=(projectId:string)=>request<Story[]>(`/projects/${projectId}/stories`);
export const getStory=(projectId:string,storyId:string)=>request<Story>(`/projects/${projectId}/stories/${storyId}`);
export const createProject=(name="Untitled Story")=>request<Project>("/projects",{method:"POST",body:JSON.stringify({name})});
export const createStory=(projectId:string,input:Omit<Story,"id"|"projectId"|"title"|"generationStatus"|"draftContent"|"createdAt"|"updatedAt"|"continuationPath">)=>request<Story>(`/projects/${projectId}/stories`,{method:"POST",body:JSON.stringify(input)});
export const getOutline=(storyId:string)=>request<StoryOutline>(`/stories/${storyId}/outline-scenes`);
export const generateOutline=(storyId:string)=>request<StoryOutline>(`/stories/${storyId}/outline/generate`,{method:"POST"});
export const createOutlineScene=(storyId:string,input:{title:string;summary:string;durationSeconds:number})=>request<OutlineScene>(`/stories/${storyId}/outline-scenes`,{method:"POST",body:JSON.stringify(input)});
export const updateOutlineScene=(storyId:string,sceneId:string,input:{title:string;summary:string;durationSeconds:number})=>request<OutlineScene>(`/stories/${storyId}/outline-scenes/${sceneId}`,{method:"PATCH",body:JSON.stringify(input)});
export const deleteOutlineScene=(storyId:string,sceneId:string)=>request<void>(`/stories/${storyId}/outline-scenes/${sceneId}`,{method:"DELETE"});
export const reorderOutlineScenes=(storyId:string,sceneIds:string[])=>request<OutlineScene[]>(`/stories/${storyId}/outline-scenes/reorder`,{method:"PATCH",body:JSON.stringify({sceneIds})});
export const listProjectCharacters=(projectId:string)=>request<Character[]>(`/projects/${projectId}/characters`);
export const listStoryCharacters=(storyId:string)=>request<Character[]>(`/stories/${storyId}/characters`);
export const createCharacter=(projectId:string,input:Omit<CharacterSuggestion,"id">)=>request<Character>(`/projects/${projectId}/characters`,{method:"POST",body:JSON.stringify(input)});
export const updateCharacter=(projectId:string,characterId:string,input:Omit<CharacterSuggestion,"id">)=>request<Character>(`/projects/${projectId}/characters/${characterId}`,{method:"PATCH",body:JSON.stringify(input)});
export const deleteCharacter=(projectId:string,characterId:string)=>request<void>(`/projects/${projectId}/characters/${characterId}`,{method:"DELETE"});
export const addCharacterToStory=(storyId:string,characterId:string)=>request<void>(`/stories/${storyId}/characters/${characterId}`,{method:"POST"});
export const removeCharacterFromStory=(storyId:string,characterId:string)=>request<void>(`/stories/${storyId}/characters/${characterId}`,{method:"DELETE"});
export const generateCharacter=(projectId:string,input:{idea:string;storyId?:string})=>request<CharacterSuggestion>(`/projects/${projectId}/characters/generate`,{method:"POST",body:JSON.stringify(input)});
const setupPath=(storyId:string,sceneId:string)=>`/stories/${storyId}/outline-scenes/${sceneId}/scene-setup`;
export const getSceneSetup=(storyId:string,sceneId:string)=>request<SceneSetup>(setupPath(storyId,sceneId));
export const createSceneSetup=(storyId:string,sceneId:string)=>request<SceneSetup>(setupPath(storyId,sceneId),{method:"POST"});
export const updateSceneBackground=(storyId:string,sceneId:string,backgroundPresetKey:string|null)=>request<SceneSetup>(`${setupPath(storyId,sceneId)}/background`,{method:"PATCH",body:JSON.stringify({backgroundPresetKey})});
export const saveSceneCharacters=(storyId:string,sceneId:string,characterIds:string[])=>request<SceneSetup>(`${setupPath(storyId,sceneId)}/characters`,{method:"PUT",body:JSON.stringify({characterIds})});
export const addSceneProp=(storyId:string,sceneId:string,propPresetKey:string)=>request<SceneSetup>(`${setupPath(storyId,sceneId)}/props`,{method:"POST",body:JSON.stringify({propPresetKey})});
export const removeSceneProp=(storyId:string,sceneId:string,propId:string)=>request<SceneSetup>(`${setupPath(storyId,sceneId)}/props/${propId}`,{method:"DELETE"});
export const saveSceneDialogue=(storyId:string,sceneId:string,lines:{speakerType:"CHARACTER"|"NARRATOR";characterId:string|null;text:string}[])=>request<SceneSetup>(`${setupPath(storyId,sceneId)}/dialogue`,{method:"PUT",body:JSON.stringify({lines})});
export const saveSceneActions=(storyId:string,sceneId:string,actions:{characterId:string;action:SceneSetupAction["action"]}[])=>request<SceneSetup>(`${setupPath(storyId,sceneId)}/actions`,{method:"PUT",body:JSON.stringify({actions})});
export const getSceneEditorHandoff=(storyId:string,sceneId:string)=>request<SceneSetup>(`${setupPath(storyId,sceneId)}/editor-handoff`);
