package com.storysprout.api.scene;

import static org.assertj.core.api.Assertions.assertThatThrownBy; import static org.mockito.Mockito.*;
import com.storysprout.api.character.CharacterRepository; import com.storysprout.api.outline.OutlineScene; import com.storysprout.api.outline.OutlineSceneRepository; import com.storysprout.api.story.Story; import com.storysprout.api.story.StoryCreationMode; import com.storysprout.api.story.StoryGenerationStatus; import com.storysprout.api.story.StoryRepository; import com.storysprout.api.story.StoryValidationException; import java.time.Instant; import java.util.List; import java.util.Optional; import java.util.UUID; import org.junit.jupiter.api.*; import org.mockito.Mock; import org.mockito.MockitoAnnotations;
class SceneSetupServiceTest {
 @Mock StoryRepository stories; @Mock OutlineSceneRepository outlines; @Mock CharacterRepository characters; @Mock SceneSetupRepository setups; SceneSetupService service; UUID storyId,sceneId; Story story; OutlineScene scene;
 @BeforeEach void setUp(){MockitoAnnotations.openMocks(this);service=new SceneSetupService(stories,outlines,characters,setups);storyId=UUID.randomUUID();sceneId=UUID.randomUUID();Instant now=Instant.now();story=new Story(storyId,UUID.randomUUID(),"Story","Idea","6_8",1,"2D","ENGLISH",StoryCreationMode.BLANK,StoryGenerationStatus.NOT_REQUESTED,null,now,now);scene=new OutlineScene(sceneId,storyId,1,"Scene","Summary",30,now,now);when(stories.findById(storyId)).thenReturn(Optional.of(story));when(outlines.findByIdAndStoryId(sceneId,storyId)).thenReturn(Optional.of(scene));}
 @Test void invalidBackgroundIsRejected(){when(setups.findByOutlineSceneId(sceneId)).thenReturn(Optional.of(setup()));assertThatThrownBy(()->service.background(storyId,sceneId,"unknown")).isInstanceOf(StoryValidationException.class);}
 @Test void duplicateCharactersAreRejected(){when(setups.findByOutlineSceneId(sceneId)).thenReturn(Optional.of(setup()));UUID c=UUID.randomUUID();assertThatThrownBy(()->service.saveCharacters(storyId,sceneId,List.of(c,c))).isInstanceOf(SceneSetupConflictException.class);verify(characters,never()).membershipExists(any(),any());}
 @Test void invalidDialogueSpeakerIsRejected(){when(setups.findByOutlineSceneId(sceneId)).thenReturn(Optional.of(setup()));assertThatThrownBy(()->service.saveDialogue(storyId,sceneId,List.of(new SceneSetupRequests.DialogueLine("ROBOT",null,"Hi")))).isInstanceOf(StoryValidationException.class);}
 @Test void invalidActionIsRejected(){when(setups.findByOutlineSceneId(sceneId)).thenReturn(Optional.of(setup()));UUID c=UUID.randomUUID();when(characters.membershipExists(storyId,c)).thenReturn(true);assertThatThrownBy(()->service.saveActions(storyId,sceneId,List.of(new SceneSetupRequests.ActionLine(c,"FLY")))).isInstanceOf(StoryValidationException.class);}
 private SceneSetup setup(){return new SceneSetup(UUID.randomUUID(),sceneId,null,List.of(),List.of(),List.of(),List.of(),Instant.now(),Instant.now());}
}
