package com.storysprout.api.scene;

import static org.assertj.core.api.Assertions.assertThat;
import java.net.URI; import java.net.http.*; import java.util.regex.*;
import org.junit.jupiter.api.*; import org.springframework.boot.test.context.SpringBootTest; import org.springframework.boot.test.web.server.LocalServerPort; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.test.context.DynamicPropertyRegistry; import org.springframework.test.context.DynamicPropertySource; import org.testcontainers.containers.PostgreSQLContainer; import org.testcontainers.junit.jupiter.Container; import org.testcontainers.junit.jupiter.Testcontainers;

@SpringBootTest(webEnvironment=SpringBootTest.WebEnvironment.RANDOM_PORT) @Testcontainers class SceneSetupControllerIntegrationTest {
 @Container static PostgreSQLContainer<?> db=new PostgreSQLContainer<>("postgres:18-alpine"); @LocalServerPort int port; @org.springframework.beans.factory.annotation.Autowired JdbcTemplate jdbc; HttpClient http=HttpClient.newHttpClient();
 @DynamicPropertySource static void db(DynamicPropertyRegistry r){r.add("spring.datasource.url",db::getJdbcUrl);r.add("spring.datasource.username",db::getUsername);r.add("spring.datasource.password",db::getPassword);}
 @BeforeEach void clean(){jdbc.update("DELETE FROM scene_setups");jdbc.update("DELETE FROM story_characters");jdbc.update("DELETE FROM characters");jdbc.update("DELETE FROM story_outline_scenes");jdbc.update("DELETE FROM stories");jdbc.update("DELETE FROM projects");}
 @Test void configureRefreshAndEditorHandoff() throws Exception {String p=id(post("/api/v1/projects","{\"name\":\"P\"}"));String s=id(post("/api/v1/projects/"+p+"/stories",story()));String scene=id(post("/api/v1/stories/"+s+"/outline-scenes","{\"title\":\"Garden\",\"summary\":\"Rabbit finds a butterfly.\",\"durationSeconds\":45}"));String c=id(post("/api/v1/projects/"+p+"/characters","{\"name\":\"Milo\",\"roleDescription\":\"Rabbit\",\"category\":\"ANIMAL\",\"visualDescription\":\"Small brown rabbit\",\"personality\":\"Curious\"}"));assertThat(post("/api/v1/stories/"+s+"/characters/"+c,null).statusCode()).isEqualTo(201);assertThat(post("/api/v1/stories/"+s+"/outline-scenes/"+scene+"/scene-setup",null).statusCode()).isEqualTo(201);assertThat(patch("/api/v1/stories/"+s+"/outline-scenes/"+scene+"/scene-setup/background","{\"backgroundPresetKey\":\"forest_day\"}").statusCode()).isEqualTo(200);assertThat(put("/api/v1/stories/"+s+"/outline-scenes/"+scene+"/scene-setup/characters","{\"characterIds\":[\""+c+"\"]}").statusCode()).isEqualTo(200);assertThat(post("/api/v1/stories/"+s+"/outline-scenes/"+scene+"/scene-setup/props","{\"propPresetKey\":\"wooden_chair\"}").statusCode()).isEqualTo(200);assertThat(put("/api/v1/stories/"+s+"/outline-scenes/"+scene+"/scene-setup/dialogue","{\"lines\":[{\"speakerType\":\"CHARACTER\",\"characterId\":\""+c+"\",\"text\":\"Look!\"},{\"speakerType\":\"NARRATOR\",\"characterId\":null,\"text\":\"Milo followed it.\"}]}").statusCode()).isEqualTo(200);assertThat(put("/api/v1/stories/"+s+"/outline-scenes/"+scene+"/scene-setup/actions","{\"actions\":[{\"characterId\":\""+c+"\",\"action\":\"WALK\"},{\"characterId\":\""+c+"\",\"action\":\"WAVE\"}]}").statusCode()).isEqualTo(200);String body=get("/api/v1/stories/"+s+"/outline-scenes/"+scene+"/scene-setup").body();assertThat(body).contains("forest_day","wooden_chair","Look!","WALK","WAVE","Milo");assertThat(get("/api/v1/stories/"+s+"/outline-scenes/"+scene+"/scene-setup/editor-handoff").body()).contains("Garden","45","forest_day");}
 @Test void invalidReferencesAndDuplicateSetupAreRejected() throws Exception {String p=id(post("/api/v1/projects","{\"name\":\"P\"}"));String p2=id(post("/api/v1/projects","{\"name\":\"Q\"}"));String s=id(post("/api/v1/projects/"+p+"/stories",story()));String scene=id(post("/api/v1/stories/"+s+"/outline-scenes","{\"title\":\"A\",\"summary\":\"B\",\"durationSeconds\":10}"));String foreign=id(post("/api/v1/projects/"+p2+"/characters","{\"name\":\"X\",\"roleDescription\":\"Child\",\"category\":\"CHILD\",\"visualDescription\":\"Blue shirt\",\"personality\":null}"));post("/api/v1/stories/"+s+"/outline-scenes/"+scene+"/scene-setup",null);assertThat(post("/api/v1/stories/"+s+"/outline-scenes/"+scene+"/scene-setup",null).statusCode()).isEqualTo(409);assertThat(put("/api/v1/stories/"+s+"/outline-scenes/"+scene+"/scene-setup/characters","{\"characterIds\":[\""+foreign+"\"]}").statusCode()).isEqualTo(409);assertThat(put("/api/v1/stories/"+s+"/outline-scenes/"+scene+"/scene-setup/actions","{\"actions\":[{\"characterId\":\""+foreign+"\",\"action\":\"FLY\"}]}").statusCode()).isEqualTo(409);}
 @Test void deletingOutlineSceneRemovesSetupChildren() throws Exception {String p=id(post("/api/v1/projects","{\"name\":\"P\"}"));String s=id(post("/api/v1/projects/"+p+"/stories",story()));String scene=id(post("/api/v1/stories/"+s+"/outline-scenes","{\"title\":\"A\",\"summary\":\"B\",\"durationSeconds\":10}"));post("/api/v1/stories/"+s+"/outline-scenes/"+scene+"/scene-setup",null);assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM scene_setups",Integer.class)).isEqualTo(1);assertThat(delete("/api/v1/stories/"+s+"/outline-scenes/"+scene).statusCode()).isEqualTo(200);assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM scene_setups",Integer.class)).isZero();}
 private String story(){return "{\"creationMode\":\"BLANK\",\"idea\":\"A rabbit finds a butterfly.\",\"targetAge\":\"6_8\",\"durationMinutes\":1,\"visualStyle\":\"2D\",\"language\":\"ENGLISH\"}";} private HttpResponse<String> req(String m,String path,String body)throws Exception{var b=HttpRequest.newBuilder(URI.create("http://localhost:"+port+path)).header("Content-Type","application/json");var q=switch(m){case"POST"->b.POST(HttpRequest.BodyPublishers.ofString(body==null?"":body)).build();case"PUT"->b.PUT(HttpRequest.BodyPublishers.ofString(body==null?"":body)).build();case"PATCH"->b.method("PATCH",HttpRequest.BodyPublishers.ofString(body==null?"":body)).build();case"DELETE"->b.DELETE().build();default->b.GET().build();};return http.send(q,HttpResponse.BodyHandlers.ofString());}private HttpResponse<String> post(String p,String b)throws Exception{return req("POST",p,b);}private HttpResponse<String> put(String p,String b)throws Exception{return req("PUT",p,b);}private HttpResponse<String> patch(String p,String b)throws Exception{return req("PATCH",p,b);}private HttpResponse<String> delete(String p)throws Exception{return req("DELETE",p,null);}private HttpResponse<String> get(String p)throws Exception{return req("GET",p,null);}private String id(HttpResponse<String> r){assertThat(r.statusCode()).isLessThan(300);Matcher m=Pattern.compile("\"id\":\"([0-9a-f-]{36})\"").matcher(r.body());if(!m.find())throw new IllegalStateException(r.body());return m.group(1);}
}
