package com.storysprout.api.outline;
import static org.assertj.core.api.Assertions.assertThat; import static org.assertj.core.api.Assertions.assertThatThrownBy; import static org.mockito.ArgumentMatchers.any; import static org.mockito.ArgumentMatchers.anyInt; import static org.mockito.Mockito.*;
import com.storysprout.api.scene.SceneSetupRepository; import com.storysprout.api.story.Story; import com.storysprout.api.story.StoryCreationMode; import com.storysprout.api.story.StoryGenerationStatus; import com.storysprout.api.story.StoryRepository; import com.storysprout.api.story.StoryValidationException; import java.time.Instant; import java.util.List; import java.util.UUID; import org.junit.jupiter.api.*; import org.mockito.Mock; import org.mockito.MockitoAnnotations;
class StoryOutlineServiceTest {
 @Mock StoryRepository stories; @Mock OutlineSceneRepository scenes; @Mock StoryOutlineGenerator generator; @Mock SceneSetupRepository sceneSetups; StoryOutlineService service; UUID storyId; Story story;
 @BeforeEach void setUp(){MockitoAnnotations.openMocks(this);service=new StoryOutlineService(stories,scenes,generator,sceneSetups);storyId=UUID.randomUUID();Instant now=Instant.now();story=new Story(storyId,UUID.randomUUID(),"Rabbit","A rabbit shares.","6_8",3,"2D","ENGLISH",StoryCreationMode.BLANK,StoryGenerationStatus.NOT_REQUESTED,null,now,now);when(stories.findById(storyId)).thenReturn(java.util.Optional.of(story));}
 @Test void varianceIsCalculatedWithoutRequiringTargetEquality(){when(scenes.findByStoryId(storyId)).thenReturn(List.of(scene(1,40),scene(2,55),scene(3,50),scene(4,45)));var s=service.getOutline(storyId);assertThat(s.targetDurationSeconds()).isEqualTo(180);assertThat(s.plannedDurationSeconds()).isEqualTo(190);assertThat(s.varianceSeconds()).isEqualTo(10);}
 @Test void addDoesNotModifyExistingDurations(){when(scenes.findByStoryId(storyId)).thenReturn(List.of(scene(1,60),scene(2,60)));when(scenes.insert(any())).thenAnswer(i->i.getArgument(0));service.create(storyId,new CreateOutlineSceneRequest("Third","Third scene",10));verify(scenes).insert(any(OutlineScene.class));verify(scenes,never()).update(any(),any(),any(),any(),anyInt());}
 @Test void deleteRemovesSetupThenScene(){UUID sceneId=UUID.randomUUID();when(scenes.findByIdAndStoryId(sceneId,storyId)).thenReturn(java.util.Optional.of(scene(sceneId,2,70)));service.delete(storyId,sceneId);verify(sceneSetups).deleteByOutlineSceneId(sceneId);verify(scenes).deleteAndCompact(sceneId,storyId);}
 @Test void reorderOnlyPassesOrderIds(){UUID first=UUID.randomUUID(),second=UUID.randomUUID();when(scenes.findByStoryId(storyId)).thenReturn(List.of(scene(first,1,40),scene(second,2,80)));service.reorder(storyId,new ReorderOutlineScenesRequest(List.of(second,first)));verify(scenes).reorder(storyId,List.of(second,first));}
 @Test void zeroAndNegativeDurationsAreRejected(){assertThatThrownBy(()->service.create(storyId,new CreateOutlineSceneRequest("A","B",0))).isInstanceOf(StoryValidationException.class);assertThatThrownBy(()->service.create(storyId,new CreateOutlineSceneRequest("A","B",-1))).isInstanceOf(StoryValidationException.class);}
 @Test void generatedDurationsDoNotNeedToMatchTarget(){when(scenes.findByStoryId(storyId)).thenReturn(List.of(),List.of(scene(1,40),scene(2,55),scene(3,50),scene(4,45)));when(generator.generate(any())).thenReturn(new StoryOutlineGenerationResult(List.of(new GeneratedOutlineScene("One","First",40),new GeneratedOutlineScene("Two","Second",55),new GeneratedOutlineScene("Three","Third",50),new GeneratedOutlineScene("Four","Fourth",45))));when(scenes.insert(any())).thenAnswer(i->i.getArgument(0));var result=service.generate(storyId);assertThat(result.plannedDurationSeconds()).isEqualTo(190);assertThat(result.varianceSeconds()).isEqualTo(10);verify(generator).generate(any());}
 private OutlineScene scene(int order,int duration){return scene(UUID.randomUUID(),order,duration);} private OutlineScene scene(UUID id,int order,int duration){return new OutlineScene(id,storyId,order,"Scene "+order,"Summary",duration,Instant.now(),Instant.now());}
}
