package com.storysprout.api.character;
import static org.assertj.core.api.Assertions.assertThat; import static org.mockito.Mockito.*;
import java.net.URI;import java.net.http.*;import java.util.regex.*;
import org.junit.jupiter.api.*;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.boot.test.web.server.LocalServerPort;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.test.context.*;import org.springframework.test.context.bean.override.mockito.MockitoBean;import org.testcontainers.containers.PostgreSQLContainer;import org.testcontainers.junit.jupiter.Container;import org.testcontainers.junit.jupiter.Testcontainers;
@SpringBootTest(webEnvironment=SpringBootTest.WebEnvironment.RANDOM_PORT) @Testcontainers class CharacterControllerIntegrationTest{
 @Container static PostgreSQLContainer<?> db=new PostgreSQLContainer<>("postgres:18-alpine"); @LocalServerPort int port; @org.springframework.beans.factory.annotation.Autowired JdbcTemplate jdbc; @MockitoBean CharacterGeneration.Generator generator; HttpClient http=HttpClient.newHttpClient();
 @DynamicPropertySource static void db(DynamicPropertyRegistry r){r.add("spring.datasource.url",db::getJdbcUrl);r.add("spring.datasource.username",db::getUsername);r.add("spring.datasource.password",db::getPassword);}
 @BeforeEach void clean(){jdbc.update("DELETE FROM story_characters");jdbc.update("DELETE FROM characters");jdbc.update("DELETE FROM story_outline_scenes");jdbc.update("DELETE FROM stories");jdbc.update("DELETE FROM projects");reset(generator);}
 @Test void reuseAndMembershipRemovalKeepCharacter() throws Exception{String pid=id(post("/api/v1/projects","{\"name\":\"P\"}"));String s1=id(post("/api/v1/projects/"+pid+"/stories",story("A")));String s2=id(post("/api/v1/projects/"+pid+"/stories",story("B")));String cid=id(post("/api/v1/projects/"+pid+"/characters","{\"name\":\"Milo\",\"roleDescription\":\"Rabbit\",\"category\":\"ANIMAL\",\"visualDescription\":\"Brown rabbit\",\"personality\":\"Kind\"}"));assertThat(post("/api/v1/stories/"+s1+"/characters/"+cid,null).statusCode()).isEqualTo(201);assertThat(post("/api/v1/stories/"+s2+"/characters/"+cid,null).statusCode()).isEqualTo(201);assertThat(delete("/api/v1/stories/"+s1+"/characters/"+cid).statusCode()).isEqualTo(200);assertThat(get("/api/v1/projects/"+pid+"/characters").body()).contains("Milo");}
 @Test void duplicateAndReferencedDeleteAreConflicts() throws Exception{String pid=id(post("/api/v1/projects","{\"name\":\"P\"}"));String sid=id(post("/api/v1/projects/"+pid+"/stories",story("A")));String cid=id(post("/api/v1/projects/"+pid+"/characters","{\"name\":\"Milo\",\"roleDescription\":\"Rabbit\",\"category\":\"ANIMAL\",\"visualDescription\":\"Brown\",\"personality\":null}"));post("/api/v1/stories/"+sid+"/characters/"+cid,null);assertThat(post("/api/v1/stories/"+sid+"/characters/"+cid,null).statusCode()).isEqualTo(409);assertThat(delete("/api/v1/projects/"+pid+"/characters/"+cid).statusCode()).isEqualTo(409);}
 private String story(String idea){return "{\"creationMode\":\"BLANK\",\"idea\":\""+idea+"\",\"targetAge\":\"6_8\",\"durationMinutes\":3,\"visualStyle\":\"2D\",\"language\":\"ENGLISH\"}";} private HttpResponse<String> req(String m,String path,String body)throws Exception{var b=HttpRequest.newBuilder(URI.create("http://localhost:"+port+path)).header("Content-Type","application/json");var q=switch(m){case"POST"->b.POST(HttpRequest.BodyPublishers.ofString(body==null?"":body)).build();case"DELETE"->b.DELETE().build();default->b.GET().build();};return http.send(q,HttpResponse.BodyHandlers.ofString());}private HttpResponse<String> post(String p,String b)throws Exception{return req("POST",p,b);}private HttpResponse<String> delete(String p)throws Exception{return req("DELETE",p,null);}private HttpResponse<String> get(String p)throws Exception{return req("GET",p,null);}private String id(HttpResponse<String> r){assertThat(r.statusCode()).isLessThan(300);Matcher m=Pattern.compile("\"id\":\"([0-9a-f-]{36})\"").matcher(r.body());if(!m.find())throw new IllegalStateException(r.body());return m.group(1);}
}
