"use client";
import Link from "next/link";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import type { PointerEvent } from "react";
import { EditorApiError, type Composition, type CompositionObject, type CompositionScene, type EditorContext, getEditorContext, saveComposition } from "../../../lib/editor";
const clamp=(n:number,min:number,max:number)=>Math.max(min,Math.min(max,n)); const clone=<T,>(v:T):T=>JSON.parse(JSON.stringify(v));
export default function EditorPage({params,searchParams}:{params:Promise<{storyId:string}>;searchParams:Promise<{scene?:string}>}){
 const [storyId,setStoryId]=useState("");const [sceneId,setSceneId]=useState("");const [ctx,setCtx]=useState<EditorContext|null>(null);const [composition,setComposition]=useState<Composition|null>(null);const [saved,setSaved]=useState("");const [selected,setSelected]=useState<string|null>(null);const [status,setStatus]=useState("Loading…");const [error,setError]=useState("");const [drag,setDrag]=useState<{id:string;offsetX:number;offsetY:number}|null>(null);const stageRef=useRef<HTMLDivElement>(null);
 useEffect(()=>{Promise.all([params,searchParams]).then(([p,q])=>{setStoryId(p.storyId);setSceneId(q.scene??"");});},[params,searchParams]);
 const load=useCallback(async()=>{if(!storyId||!sceneId)return;setStatus("Loading…");setError("");try{const c=await getEditorContext(storyId,sceneId);setCtx(c);setComposition(clone(c.composition.compositionJson));setSaved(JSON.stringify(c.composition.compositionJson));setStatus("Saved");setSelected(null);}catch(e){setError(e instanceof Error?e.message:"Unable to load Editor");setStatus("Load failed");}},[storyId,sceneId]); useEffect(()=>{load();},[load]);
 const dirty=!!composition&&JSON.stringify(composition)!==saved;
 useEffect(()=>{const h=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue="";}};const key=(e:KeyboardEvent)=>{if(e.key==="Escape")setSelected(null);if((e.key==="Delete"||e.key==="Backspace")&&selected){setComposition(c=>c?{...c,scenes:c.scenes.map(s=>({...s,objects:s.objects.filter(o=>o.id!==selected)}))}:c);setSelected(null);}};window.addEventListener("beforeunload",h);window.addEventListener("keydown",key);return()=>{window.removeEventListener("beforeunload",h);window.removeEventListener("keydown",key);};},[dirty,selected]);
 const scene=composition?.scenes[0];const object=scene?.objects.find(o=>o.id===selected)||null;const characterById=useMemo(()=>new Map((ctx?.characters??[]).map(c=>[c.id,c])),[ctx]);const propByAsset=useMemo(()=>new Map((ctx?.propOptions??[]).map(p=>[`prop-preset:${p.key}`,p])),[ctx]);const label=(o:CompositionObject)=>o.objectType==="CHARACTER"?(characterById.get(o.assetId)?.name??"Character"):(propByAsset.get(o.assetId)?.name??"Prop");
 const updateObject=(id:string,fn:(o:CompositionObject)=>CompositionObject)=>setComposition(c=>c?({...c,scenes:c.scenes.map(s=>({...s,objects:s.objects.map(o=>o.id===id?fn(o):o)}))}):c); const updateScene=(fn:(s:CompositionScene)=>CompositionScene)=>setComposition(c=>c?({...c,scenes:c.scenes.map(s=>s.id===scene?.id?fn(s):s)}):c);
 const addObject=(type:"CHARACTER"|"PROP",assetId:string)=>{if(!composition||!scene)return;const o:CompositionObject={id:crypto.randomUUID(),objectType:type,assetId,x:type==="CHARACTER"?320:600,y:type==="CHARACTER"?520:760,scale:1,rotation:0,visible:true};setComposition({...composition,scenes:composition.scenes.map(s=>s.id===scene.id?{...s,objects:[...s.objects,o]}:s)});setSelected(o.id);};
 const pointerDown=(e:PointerEvent,id:string)=>{const el=stageRef.current;if(!el||!scene)return;const r=el.getBoundingClientRect();const o=scene.objects.find(x=>x.id===id);if(!o)return;setSelected(id);setDrag({id,offsetX:(e.clientX-r.left)*(1920/r.width)-o.x,offsetY:(e.clientY-r.top)*(1080/r.height)-o.y});(e.currentTarget as HTMLElement).setPointerCapture(e.pointerId);};const pointerMove=(e:PointerEvent)=>{if(!drag||!stageRef.current)return;const r=stageRef.current.getBoundingClientRect();const x=clamp((e.clientX-r.left)*(1920/r.width)-drag.offsetX,0,1920);const y=clamp((e.clientY-r.top)*(1080/r.height)-drag.offsetY,0,1080);updateObject(drag.id,o=>({...o,x,y}));};
 const save=async()=>{if(!composition||!ctx)return;setStatus("Saving…");setError("");try{const r=await saveComposition(storyId,sceneId,ctx.composition.version,composition);setComposition(clone(r.compositionJson));setSaved(JSON.stringify(r.compositionJson));setCtx(c=>c?({...c,composition:r}):c);setStatus("Saved");}catch(e){if(e instanceof EditorApiError&&e.status===409){setStatus("Conflict — reload required");setError(e.message);}else{setStatus("Save failed");setError(e instanceof Error?e.message:"Save failed");}}};
 if(!storyId||!sceneId)return <main className="p-10">Loading Editor…</main>;if(error&&!ctx)return <main className="min-h-screen bg-slate-50 p-10"><div className="mx-auto max-w-xl rounded-2xl bg-white p-8 shadow"><h1 className="text-xl font-bold">Editor could not open</h1><p className="mt-3 text-red-700">{error}</p><button onClick={load} className="mt-5 rounded-lg bg-slate-900 px-4 py-2 text-white">Retry</button></div></main>;if(!ctx||!composition||!scene)return <main className="p-10">{status}</main>;
 const backgroundName=scene.background?.assetId?.replace("background-preset:",""); const moveLayer=(direction:"backward"|"forward"|"back"|"front")=>updateScene(s=>{const i=s.objects.findIndex(x=>x.id===selected);if(i<0)return s;const a=[...s.objects];if(direction==="backward"&&i>0)[a[i-1],a[i]]=[a[i],a[i-1]];if(direction==="forward"&&i<a.length-1)[a[i],a[i+1]]=[a[i+1],a[i]];if(direction==="back"){const [x]=a.splice(i,1);a.unshift(x);}if(direction==="front"){const [x]=a.splice(i,1);a.push(x);}return Object.assign({},s,{objects:a});});
 return <main className="min-h-screen bg-slate-100 text-slate-950"><header className="flex h-16 items-center justify-between border-b bg-white px-5"><div><div className="text-xs font-semibold uppercase tracking-widest text-indigo-600">StorySprout Editor</div><div className="font-bold">{ctx.storyTitle} · Scene {ctx.sceneOrder}: {ctx.sceneTitle}</div></div><div className="flex items-center gap-3"><span aria-live="polite" className="text-sm text-slate-600">{dirty?"Unsaved changes":status}</span><button onClick={save} disabled={!dirty||status==="Saving…"} className="rounded-lg bg-indigo-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-40">Save</button><Link href={`/stories/${storyId}/scene-setup?scene=${sceneId}`} className="rounded-lg border px-4 py-2 text-sm">Back</Link></div></header>{error&&<div role="alert" className="border-b bg-red-50 px-5 py-2 text-sm text-red-800">{error} {status.includes("Conflict")&&<button onClick={load} className="ml-2 font-semibold underline">Reload latest</button>}</div>}
 <div className="grid min-h-[calc(100vh-112px)] grid-cols-[230px_minmax(500px,1fr)_270px] gap-4 p-4"><aside className="rounded-2xl border bg-white p-4"><h2 className="font-bold">Scene Objects</h2><div className="mt-3 space-y-2">{scene.objects.map(o=><div key={o.id} className={`flex items-center gap-2 rounded-lg border p-2 ${selected===o.id?"border-indigo-500 bg-indigo-50":""}`}><button onClick={()=>setSelected(o.id)} className="min-w-0 flex-1 text-left text-sm font-medium">{label(o)} <span className="text-xs text-slate-400">{o.objectType}</span></button><button aria-label={`Toggle visibility for ${label(o)}`} onClick={()=>updateObject(o.id,x=>({...x,visible:!x.visible}))} className="text-xs">{o.visible?"◉":"○"}</button></div>)}</div><div className="mt-5 space-y-2"><div className="text-xs font-semibold uppercase text-slate-500">Add Character</div>{ctx.characters.map(c=><button key={c.id} onClick={()=>addObject("CHARACTER",c.id)} className="block w-full rounded-lg border px-3 py-2 text-left text-sm">+ {c.name}</button>)}<div className="pt-2 text-xs font-semibold uppercase text-slate-500">Add Prop</div>{ctx.propOptions.map(p=><button key={p.key} onClick={()=>addObject("PROP",`prop-preset:${p.key}`)} className="block w-full rounded-lg border px-3 py-2 text-left text-sm">+ {p.name}</button>)}</div></aside>
 <section className="flex flex-col gap-3"><div className="flex-1 rounded-2xl border bg-slate-200 p-4"><div ref={stageRef} onPointerMove={pointerMove} onPointerUp={()=>setDrag(null)} onPointerCancel={()=>setDrag(null)} className="relative mx-auto aspect-video w-full max-w-5xl overflow-hidden rounded-xl border-2 border-slate-300 bg-white" aria-label="1920 by 1080 logical stage">{scene.objects.map(o=><div key={o.id} onPointerDown={e=>pointerDown(e,o.id)} className={`absolute flex h-20 w-28 -translate-x-1/2 -translate-y-1/2 select-none items-center justify-center rounded-xl border-2 text-xs font-bold shadow ${selected===o.id?"border-indigo-600 ring-4 ring-indigo-200":"border-slate-500"} ${o.visible?"":"opacity-25"}`} style={{left:`${o.x/1920*100}%`,top:`${o.y/1080*100}%`,transform:`translate(-50%,-50%) scale(${o.scale})`}}>{label(o)}{selected===o.id&&<button aria-label={`Resize ${label(o)}`} onPointerDown={e=>{e.stopPropagation();const start=e.clientX;const startScale=o.scale;const move=(ev:globalThis.PointerEvent)=>updateObject(o.id,x=>({...x,scale:clamp(startScale+(ev.clientX-start)/200,0.25,3)}));const up=()=>{window.removeEventListener("pointermove",move);window.removeEventListener("pointerup",up)};window.addEventListener("pointermove",move);window.addEventListener("pointerup",up)}} className="absolute bottom-[-9px] right-[-9px] h-4 w-4 rounded-full border bg-white">↘</button>}</div>)}</div></div><div className="rounded-xl border bg-white px-4 py-3 text-sm text-slate-500">Timeline — Coming next · no timing controls in Editor V1</div></section>
 <aside className="rounded-2xl border bg-white p-4"><h2 className="font-bold">Properties</h2>{object?<div className="mt-4 space-y-3"><div className="text-sm font-semibold">{label(object)}</div><div className="text-xs text-slate-500">Type: {object.objectType} · Rotation: {object.rotation}</div><label className="block text-sm">X<input aria-label="X" type="number" value={object.x} onChange={e=>updateObject(object.id,o=>({...o,x:clamp(Number(e.target.value)||0,0,1920)}))} className="mt-1 w-full rounded border p-2"/></label><label className="block text-sm">Y<input aria-label="Y" type="number" value={object.y} onChange={e=>updateObject(object.id,o=>({...o,y:clamp(Number(e.target.value)||0,0,1080)}))} className="mt-1 w-full rounded border p-2"/></label><label className="block text-sm">Scale<input aria-label="Scale" type="number" step="0.05" min="0.25" max="3" value={object.scale} onChange={e=>updateObject(object.id,o=>({...o,scale:clamp(Number(e.target.value)||1,0.25,3)}))} className="mt-1 w-full rounded border p-2"/></label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={object.visible} onChange={e=>updateObject(object.id,o=>({...o,visible:e.target.checked}))}/> Visible</label><button onClick={()=>updateObject(object.id,o=>({...o,x:960,y:540,scale:1,rotation:0}))} className="w-full rounded border px-2 py-2 text-sm">Reset transform</button><button onClick={()=>setComposition(c=>c?{...c,scenes:c.scenes.map(s=>({...s,objects:s.objects.filter(x=>x.id!==object.id)}))}:c)} className="w-full rounded border border-red-200 px-2 py-2 text-sm text-red-700">Delete</button><div className="grid grid-cols-2 gap-2"><button onClick={()=>moveLayer("back")} className="rounded border px-2 py-2 text-sm">Send to Back</button><button onClick={()=>moveLayer("front")} className="rounded border px-2 py-2 text-sm">Bring to Front</button><button onClick={()=>moveLayer("backward")} className="rounded border px-2 py-2 text-sm">Send Backward</button><button onClick={()=>moveLayer("forward")} className="rounded border px-2 py-2 text-sm">Bring Forward</button></div></div>:<div className="mt-4 text-sm text-slate-500">Select an object to edit its properties.</div>}<div className="mt-6 border-t pt-4"><div className="text-sm font-semibold">Background</div><div className="mt-2 text-xs text-slate-500">{backgroundName??"None"}</div><div className="mt-2 space-y-1">{ctx.backgroundOptions.map(b=><button key={b.key} onClick={()=>updateScene(s=>({...s,background:{assetId:`background-preset:${b.key}`}}))} className="block w-full rounded border px-2 py-1 text-left text-xs">{b.name}</button>)}<button onClick={()=>updateScene(s=>{const x={...s};delete x.background;return x;})} className="w-full rounded border px-2 py-1 text-xs">Remove background</button></div></div></aside></div></main>;
}
