/* eslint-disable react-hooks/set-state-in-effect */
"use client";
import Link from "next/link";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import type { PointerEvent } from "react";
import { EditorApiError, type Composition, type CompositionObject, type CompositionScene, type EditorContext, getEditorContext, saveComposition } from "../../../lib/editor";
import { getRenderJob, requestRender, retryRender, type RenderJob } from "../../../lib/render";
import { Button, SaveState, cx } from "../../../components/ui";
const clamp=(n:number,min:number,max:number)=>Math.max(min,Math.min(max,n)); const clone=<T,>(v:T):T=>JSON.parse(JSON.stringify(v));
function extractComposition(c:any):Composition|null{if(!c)return null;let raw=c.composition?.compositionJson??c.compositionJson??c.composition??c;if(typeof raw==="string"){try{raw=JSON.parse(raw);}catch{}}if(raw&&typeof raw.compositionJson==="object"&&raw.compositionJson!==null){raw=raw.compositionJson;}if(typeof raw==="string"){try{raw=JSON.parse(raw);}catch{}}if(raw&&Array.isArray(raw.scenes)){return raw as Composition;}return null;}

export default function EditorPage({params,searchParams}:{params:Promise<{storyId:string}>;searchParams:Promise<{scene?:string}>}){
 const [storyId,setStoryId]=useState("");const [sceneId,setSceneId]=useState("");const [ctx,setCtx]=useState<EditorContext|null>(null);const [composition,setComposition]=useState<Composition|null>(null);const [saved,setSaved]=useState("");const [selected,setSelected]=useState<string|null>(null);const [status,setStatus]=useState("Loading…");const [error,setError]=useState("");const [renderJob,setRenderJob]=useState<RenderJob|null>(null);const [renderError,setRenderError]=useState("");const [renderBusy,setRenderBusy]=useState(false);const [drag,setDrag]=useState<{id:string;offsetX:number;offsetY:number}|null>(null);const stageRef=useRef<HTMLDivElement>(null);
 useEffect(()=>{Promise.all([params,searchParams]).then(([p,q])=>{setStoryId(p.storyId);setSceneId(q.scene??"");});},[params,searchParams]);
  const load=useCallback(async()=>{if(!storyId||!sceneId)return;setStatus("Loading…");setError("");try{const c=await getEditorContext(storyId,sceneId);setCtx(c);let compData:any=extractComposition(c);if(!compData||!Array.isArray(compData.scenes)||compData.scenes.length===0){const defaultScene:CompositionScene={id:c.outlineSceneId||sceneId,name:c.sceneTitle||"Scene 1",durationMs:(c.plannedDurationSeconds||45)*1000,background:c.sceneSetup?.backgroundPresetKey?{assetId:`background-preset:${c.sceneSetup.backgroundPresetKey}`}:undefined,objects:[],timeline:[]};compData={schemaVersion:"1.1",projectId:(c as any).projectId||c.storyId,width:1920,height:1080,fps:30,durationMs:(c.plannedDurationSeconds||45)*1000,scenes:[defaultScene]};}if(compData&&compData.scenes&&compData.scenes[0]){const existingObjects:CompositionObject[]=compData.scenes[0].objects||[];const setupChars=c.sceneSetup?.characters||[];const missingChars=setupChars.filter(sc=>{const charId=(sc as any).characterId||sc.id;return !existingObjects.some(o=>o.objectType==="CHARACTER"&&o.assetId===charId);});if(missingChars.length>0){const newObjects=[...existingObjects];missingChars.forEach((sc,idx)=>{const charId=(sc as any).characterId||sc.id;newObjects.push({id:crypto.randomUUID(),objectType:"CHARACTER",assetId:charId,x:clamp(320+(existingObjects.filter(o=>o.objectType==="CHARACTER").length+idx)*300,0,1920),y:540,scale:1,rotation:0,visible:true});});compData={...compData,scenes:compData.scenes.map((s:any,i:number)=>i===0?{...s,objects:newObjects}:s)};}}setComposition(clone(compData));setSaved(JSON.stringify(compData));setStatus("Saved");setSelected(null);}catch(e){setError(e instanceof Error?e.message:"Unable to load Editor");setStatus("Load failed");}},[storyId,sceneId]); useEffect(()=>{load();},[load]);
  const dirty=!!composition&&JSON.stringify(composition)!==saved; useEffect(()=>{const h=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue="";}};const key=(e:KeyboardEvent)=>{if(e.key==="Escape")setSelected(null);if((e.key==="Delete"||e.key==="Backspace")&&selected){setComposition(c=>c?{...c,scenes:c.scenes.map(s=>({...s,objects:s.objects.filter(o=>o.id!==selected)}))}:c);setSelected(null);}};window.addEventListener("beforeunload",h);window.addEventListener("keydown",key);return()=>{window.removeEventListener("beforeunload",h);window.removeEventListener("keydown",key);};},[dirty,selected]);
  useEffect(()=>{if(!renderJob||!storyId||!sceneId||renderJob.status==="COMPLETED"||renderJob.status==="FAILED")return;const timer=window.setInterval(async()=>{try{setRenderJob(await getRenderJob(storyId,sceneId,renderJob.id));}catch(e){setRenderError(e instanceof Error?e.message:"Unable to refresh render status");}},1500);return()=>window.clearInterval(timer);},[renderJob?.id,renderJob?.status,storyId,sceneId]);
  const startRender=async()=>{if(dirty||!storyId||!sceneId)return;setRenderBusy(true);setRenderError("");try{setRenderJob(await requestRender(storyId,sceneId));}catch(e){setRenderError(e instanceof Error?e.message:"Unable to request render");}finally{setRenderBusy(false);}};
  const retryCurrentRender=async()=>{if(!renderJob)return;setRenderBusy(true);setRenderError("");try{setRenderJob(await retryRender(storyId,sceneId,renderJob.id));}catch(e){setRenderError(e instanceof Error?e.message:"Unable to retry render");}finally{setRenderBusy(false);}};
  const scene=composition?.scenes?.[0];const object=scene?.objects.find(o=>o.id===selected)||null;const characterById=useMemo(()=>new Map((ctx?.characters??[]).map(c=>[c.id,c])),[ctx]);const propByAsset=useMemo(()=>new Map((ctx?.propOptions??[]).map(p=>[`prop-preset:${p.key}`,p])),[ctx]);const label=(o:CompositionObject)=>o.objectType==="CHARACTER"?(characterById.get(o.assetId)?.name??"Character"):(propByAsset.get(o.assetId)?.name??"Prop");
  const updateObject=(id:string,fn:(o:CompositionObject)=>CompositionObject)=>setComposition(c=>c?({...c,scenes:c.scenes.map(s=>({...s,objects:s.objects.map(o=>o.id===id?fn(o):o)}))}):c); const updateScene=(fn:(s:CompositionScene)=>CompositionScene)=>setComposition(c=>c?({...c,scenes:c.scenes.map(s=>s.id===scene?.id?fn(s):s)}):c);
  const addObject=(type:"CHARACTER"|"PROP",assetId:string)=>{if(!composition||!scene)return;const o:CompositionObject={id:crypto.randomUUID(),objectType:type,assetId,x:type==="CHARACTER"?320:600,y:type==="CHARACTER"?520:760,scale:1,rotation:0,visible:true};setComposition({...composition,scenes:composition.scenes.map(s=>s.id===scene.id?{...s,objects:[...s.objects,o]}:s)});setSelected(o.id);};
  const pointerDown=(e:PointerEvent,id:string)=>{const el=stageRef.current;if(!el||!scene)return;const r=el.getBoundingClientRect();const o=scene.objects.find(x=>x.id===id);if(!o)return;setSelected(id);setDrag({id,offsetX:(e.clientX-r.left)*(1920/r.width)-o.x,offsetY:(e.clientY-r.top)*(1080/r.height)-o.y});(e.currentTarget as HTMLElement).setPointerCapture(e.pointerId);};const pointerMove=(e:PointerEvent)=>{if(!drag||!stageRef.current)return;const r=stageRef.current.getBoundingClientRect();const x=clamp((e.clientX-r.left)*(1920/r.width)-drag.offsetX,0,1920);const y=clamp((e.clientY-r.top)*(1080/r.height)-drag.offsetY,0,1080);updateObject(drag.id,o=>({...o,x,y}));};
  const save=async()=>{if(!composition||!ctx)return;setStatus("Saving…");setError("");try{const projId=(ctx.composition as any)?.projectId||(ctx.composition?.compositionJson as any)?.projectId||(composition as any)?.projectId||ctx.storyId;const version=typeof ctx.composition?.version==="number"?ctx.composition.version:1;const safeComp:Composition={schemaVersion:"1.1",projectId:projId,width:1920,height:1080,fps:30,durationMs:composition.durationMs||ctx.plannedDurationSeconds*1000,scenes:composition.scenes.map((s,i)=>i===0?{id:ctx.outlineSceneId,name:s.name||ctx.sceneTitle,durationMs:s.durationMs||ctx.plannedDurationSeconds*1000,background:s.background?.assetId?{assetId:s.background.assetId}:undefined,objects:(s.objects||[]).map(o=>({id:o.id||crypto.randomUUID(),objectType:o.objectType,assetId:o.assetId,x:clamp(typeof o.x==="number"&&!isNaN(o.x)?o.x:320,0,1920),y:clamp(typeof o.y==="number"&&!isNaN(o.y)?o.y:540,0,1080),scale:clamp(typeof o.scale==="number"&&!isNaN(o.scale)?o.scale:1,0.25,3),rotation:0,visible:typeof o.visible==="boolean"?o.visible:true})),timeline:[]}:s)};const r=await saveComposition(storyId,sceneId,version,safeComp);let compJson:any=extractComposition(r)||safeComp;compJson={...compJson,projectId:r?.projectId||projId};const finalComp=clone(compJson);setComposition(finalComp);setSaved(JSON.stringify(finalComp));setCtx(c=>c?({...c,composition:r?{...r,compositionJson:finalComp}:c.composition}):c);setStatus("Saved");}catch(e){console.error("Save error:",e);if(e instanceof EditorApiError&&e.status===409){setStatus("Conflict — reload required");setError(e.message);}else{setStatus("Save failed");setError(e instanceof Error?e.message:"Save failed");}}};
  if(!storyId||!sceneId)return <main className="p-10">Loading Editor…</main>;if(error&&!ctx)return <main className="min-h-screen bg-slate-50 p-10"><div className="mx-auto max-w-xl rounded-2xl bg-white p-8 shadow"><h1 className="text-xl font-bold">Editor could not open</h1><p className="mt-3 text-red-700">{error}</p><button onClick={load} className="mt-5 rounded-lg bg-slate-900 px-4 py-2 text-white">Retry</button></div></main>;if(!ctx||!composition||!scene)return <main className="p-10">{status}</main>;
  const backgroundName=scene.background?.assetId?.replace("background-preset:",""); const moveLayer=(direction:"backward"|"forward"|"back"|"front")=>updateScene(s=>{const i=s.objects.findIndex(x=>x.id===selected);if(i<0)return s;const a=[...s.objects];if(direction==="backward"&&i>0)[a[i-1],a[i]]=[a[i],a[i-1]];if(direction==="forward"&&i<a.length-1)[a[i],a[i+1]]=[a[i+1],a[i]];if(direction==="back"){const [x]=a.splice(i,1);a.unshift(x);}if(direction==="front"){const [x]=a.splice(i,1);a.push(x);}return Object.assign({},s,{objects:a});});
  
  const saveState = status.includes("Conflict") ? "conflict" : status === "Save failed" ? "error" : status === "Saving…" ? "saving" : dirty ? "unsaved" : "saved";

  return (
    <main className="min-h-screen bg-[var(--ss-editor-bg)] text-slate-950">
      <header className="border-b border-[var(--ss-editor-border-strong)] bg-[var(--ss-editor-header)] text-white">
        <div className="mx-auto flex min-h-16 max-w-[1600px] items-center justify-between gap-4 px-4 sm:px-6">
          <div className="flex min-w-0 items-center gap-3">
            <Link href={'/stories/' + storyId + '/scene-setup?scene=' + sceneId} aria-label="Back to Scene Setup" className="grid h-9 w-9 shrink-0 place-items-center rounded-lg text-slate-300 hover:bg-white/10 hover:text-white focus:outline-none focus-visible:ring-2 focus-visible:ring-indigo-400">←</Link>
            <div className="hidden items-center gap-2 sm:flex"><span className="grid h-8 w-8 place-items-center rounded-lg bg-indigo-500 text-xs font-black text-white">S</span><span className="text-sm font-semibold tracking-tight text-white">StorySprout</span></div>
            <div className="hidden h-6 w-px bg-white/10 sm:block" />
            <div className="min-w-0"><div className="truncate text-[10px] font-semibold uppercase tracking-[.14em] text-slate-500">Project → Story → Scene</div><div className="truncate text-sm font-semibold">{ctx.storyTitle}</div><div className="truncate text-xs text-slate-400">Scene {ctx.sceneOrder} · {ctx.sceneTitle}</div></div>
          </div>
          <div className="flex shrink-0 items-center gap-2"><SaveState state={saveState}/><Link href={`/stories/${storyId}/preview?scene=${sceneId}`} aria-disabled={dirty} onClick={e=>{if(dirty)e.preventDefault();}} className={cx("rounded-[10px] border border-[var(--ss-editor-border-strong)] px-3 py-2 text-sm font-semibold text-slate-200 hover:bg-white/10 focus:outline-none focus-visible:ring-2 focus-visible:ring-indigo-400",dirty&&"pointer-events-none opacity-50")}>Preview</Link><Button onClick={startRender} disabled={dirty||renderBusy||status==="Saving…"} className="min-w-[88px]">Render</Button><Button onClick={save} disabled={!dirty || status === "Saving…"} className="min-w-[92px] bg-white text-slate-900 hover:bg-slate-100 disabled:bg-white/30 disabled:text-white/60">Save</Button></div>
        </div>
      </header>
      {error && <div role="alert" className="border-b border-red-200 bg-red-50 px-4 py-2 text-sm text-red-800"><div className="mx-auto flex max-w-[1600px] items-center justify-between gap-4"><span>{error}</span>{status.includes("Conflict") && <button onClick={load} className="font-semibold underline focus:outline-none focus-visible:ring-2 focus-visible:ring-red-600">Reload latest</button>}</div></div>}
      {(renderJob || renderError) && <div className="border-b border-indigo-200 bg-indigo-50 px-4 py-3"><div className="mx-auto flex max-w-[1600px] flex-wrap items-center justify-between gap-3 text-sm"><div><span className="font-semibold text-indigo-950">Render</span>{renderJob && <span className="ml-2 text-indigo-800">{renderJob.status.toLowerCase()} · {renderJob.progress}% · Composition v{renderJob.compositionVersion}</span>}{renderError && <span role="alert" className="ml-2 text-red-700">{renderError}</span>}{renderJob?.status==="FAILED" && renderJob.failureMessage && <p className="mt-1 text-xs text-red-700">{renderJob.failureMessage}</p>}</div><div className="flex items-center gap-2">{renderJob?.status==="COMPLETED" && renderJob.artifactUrl && <a href={renderJob.artifactUrl} target="_blank" rel="noreferrer" className="font-semibold text-indigo-800 underline">Open MP4</a>}{renderJob?.status==="FAILED" && <Button type="button" variant="secondary" onClick={retryCurrentRender} disabled={renderBusy}>Retry</Button>}</div></div></div>}
      <div className="mx-auto grid min-h-[calc(100vh-112px)] max-w-[1600px] grid-cols-1 gap-px bg-slate-700/50 lg:grid-cols-[220px_minmax(0,1fr)_280px]">
        <aside aria-label="Scene assets" className="bg-[var(--ss-editor-panel)] p-3 text-white lg:overflow-y-auto">
          <div className="flex items-center justify-between px-2 py-2"><div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-slate-500">Toolkit</p><h2 className="mt-1 text-sm font-bold">Scene assets</h2></div><span className="text-[10px] text-slate-500">V1</span></div>
          <div className="mt-3 space-y-5">
            <section><div className="mb-2 px-2 text-[10px] font-bold uppercase tracking-[.14em] text-slate-500">Story Characters</div><p className="mb-2 px-2 text-[10px] leading-4 text-slate-600">Reusable Project characters staged in this Story.</p><div className="space-y-1">{ctx.characters.map(c => <button key={c.id} onClick={() => addObject("CHARACTER", c.id)} className="flex w-full items-center gap-2 rounded-xl px-2 py-2 text-left transition hover:bg-white/7 focus:outline-none focus-visible:ring-2 focus-visible:ring-indigo-400"><span aria-hidden="true" className="grid h-9 w-9 shrink-0 place-items-center rounded-lg border border-indigo-400/20 bg-indigo-500/10 text-xs font-bold text-indigo-300">{c.name.slice(0, 1).toUpperCase()}</span><span className="min-w-0 flex-1"><span className="block truncate text-xs font-semibold">{c.name}</span><span className="block truncate text-[10px] text-slate-500">{c.category}</span></span><span className="text-slate-500">+</span></button>)}{!ctx.characters.length && <p className="px-2 text-xs leading-5 text-slate-500">No Story Characters available.</p>}</div></section>
            <section><div className="mb-2 px-2 text-[10px] font-bold uppercase tracking-[.14em] text-slate-500">Props</div><div className="space-y-1">{ctx.propOptions.map(p => <button key={p.key} onClick={() => addObject("PROP", "prop-preset:" + p.key)} className="flex w-full items-center gap-2 rounded-xl px-2 py-2 text-left transition hover:bg-white/7 focus:outline-none focus-visible:ring-2 focus-visible:ring-amber-400"><span aria-hidden="true" className="grid h-9 w-9 shrink-0 place-items-center rounded-lg border border-amber-400/20 bg-amber-500/10 text-xs font-bold text-amber-300">P</span><span className="min-w-0 flex-1"><span className="block truncate text-xs font-semibold">{p.name}</span><span className="block truncate text-[10px] text-slate-500">{p.category}</span></span><span className="text-slate-500">+</span></button>)}{!ctx.propOptions.length && <p className="px-2 text-xs leading-5 text-slate-500">No controlled Props available.</p>}</div></section>
            <section><div className="mb-2 px-2 text-[10px] font-bold uppercase tracking-[.14em] text-slate-500">In scene</div><div className="space-y-1">{scene.objects.map(o => <div key={o.id} className={cx("flex items-center gap-2 rounded-xl border px-2 py-2", selected === o.id ? "border-indigo-400/50 bg-indigo-500/10" : "border-transparent bg-white/3")}><button onClick={() => setSelected(o.id)} aria-pressed={selected === o.id} className="min-w-0 flex-1 text-left focus:outline-none focus-visible:ring-2 focus-visible:ring-indigo-400"><span className="block truncate text-xs font-semibold">{label(o)}</span><span className="text-[10px] text-slate-500">{o.objectType}</span></button><button aria-label={(o.visible ? "Hide " : "Show ") + label(o)} onClick={() => updateObject(o.id, x => ({ ...x, visible: !x.visible }))} className="rounded-md px-2 py-1 text-xs text-slate-500 hover:bg-white/10 hover:text-white focus:outline-none focus-visible:ring-2 focus-visible:ring-indigo-400">{o.visible ? "Visible" : "Hidden"}</button></div>)}{!scene.objects.length && <p className="rounded-xl border border-dashed border-[var(--ss-editor-border-strong)] px-3 py-4 text-xs leading-5 text-slate-500">Nothing on stage yet. Add a character or prop above.</p>}</div></section>
          </div>
        </aside>
        <section className="flex min-w-0 flex-col bg-[var(--ss-editor-stage-shell)] p-3 sm:p-4" aria-label="Story stage">
          <div className="mb-3 flex items-center justify-between gap-3 px-1 text-xs text-slate-400"><span>Stage · 1920 × 1080</span><span className="truncate">{ctx.sceneSummary}</span></div>
          <div className="flex min-h-[420px] flex-1 items-center justify-center rounded-[18px] border border-[var(--ss-editor-border)] bg-[var(--ss-editor-stage)] p-3 sm:p-6">
            <div ref={stageRef} onPointerMove={pointerMove} onPointerUp={() => setDrag(null)} onPointerCancel={() => setDrag(null)} className="relative aspect-video w-full max-w-[1100px] overflow-hidden rounded-[14px] border border-slate-400/30 bg-white shadow-[0_20px_60px_rgba(0,0,0,.35)]" aria-label="1920 by 1080 logical stage">
              {backgroundName ? <div className="absolute inset-0 bg-slate-100" aria-label={'Background ' + backgroundName}><div className="absolute inset-x-0 bottom-0 h-[24%] bg-slate-200/80"/><div className="absolute left-5 top-5 rounded-lg border border-slate-200 bg-white/90 px-2.5 py-1 text-[10px] font-semibold uppercase tracking-[.12em] text-slate-500">{backgroundName}</div></div> : <div className="absolute inset-0 grid place-items-center bg-slate-50"><div className="max-w-sm px-6 text-center"><div className="text-xs font-bold uppercase tracking-[.16em] text-slate-400">Empty stage</div><h2 className="mt-2 text-lg font-bold text-slate-800">Start directing the scene</h2><p className="mt-2 text-sm leading-6 text-slate-500">Add a background, character or prop from the toolkit.</p></div></div>}
              {scene.objects.map(o => <button key={o.id} type="button" onClick={() => setSelected(o.id)} onPointerDown={e => pointerDown(e, o.id)} onKeyDown={e => { if (e.key === "Enter" || e.key === " ") { e.preventDefault(); setSelected(o.id); } }} aria-label={label(o) + ", " + o.objectType} aria-pressed={selected === o.id} className={cx("absolute flex h-20 w-28 -translate-x-1/2 -translate-y-1/2 select-none items-center justify-center rounded-xl border-2 text-xs font-bold shadow-md transition-[box-shadow,border-color,opacity] duration-150 focus:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500", selected === o.id ? "border-indigo-600 bg-white ring-4 ring-indigo-200" : "border-slate-400 bg-white/95 hover:border-slate-600", o.visible ? "opacity-100" : "opacity-25")} style={{left: (o.x / 1920 * 100) + "%", top: (o.y / 1080 * 100) + "%", transform: "translate(-50%,-50%) scale(" + o.scale + ")"}}><span className={cx("grid h-10 w-10 place-items-center rounded-lg text-xs font-bold", o.objectType === "CHARACTER" ? "bg-indigo-50 text-indigo-700" : "bg-amber-50 text-amber-700")}>{o.objectType === "CHARACTER" ? label(o).slice(0, 1).toUpperCase() : "P"}</span><span className="sr-only">{label(o)}</span>{selected === o.id && <span aria-hidden="true" onPointerDown={e => {e.stopPropagation();const start=e.clientX;const startScale=o.scale;const move=(ev:globalThis.PointerEvent)=>updateObject(o.id,x=>({...x,scale:clamp(startScale+(ev.clientX-start)/200,0.25,3)}));const up=()=>{window.removeEventListener("pointermove",move);window.removeEventListener("pointerup",up)};window.addEventListener("pointermove",move);window.addEventListener("pointerup",up)}} className="absolute -bottom-2 -right-2 h-4 w-4 cursor-nwse-resize rounded-full border-2 border-indigo-600 bg-white shadow-sm"/>}</button>)}
            </div>
          </div>
          <div className="mt-3 flex items-center justify-between rounded-xl border border-[var(--ss-editor-border)] bg-[var(--ss-editor-panel)] px-3 py-2 text-xs"><span className="font-semibold text-slate-400">Timeline</span><span className="text-slate-500">Coming next · no timing controls in Editor V1</span></div>
        </section>
        <aside aria-label="Properties inspector" className="bg-[var(--ss-editor-panel)] p-4 text-white lg:overflow-y-auto">
          <div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-slate-500">Inspector</p><h2 className="mt-1 text-sm font-bold">Properties</h2></div>{object && <span className="rounded-full border border-[var(--ss-editor-border-strong)] px-2 py-1 text-[10px] font-semibold text-slate-400">{object.objectType}</span>}</div>
          <div className="mt-5 space-y-5">
            {object ? <>
              <section><h3 className="text-[11px] font-bold uppercase tracking-[.14em] text-slate-500">Object</h3><div className="mt-3 rounded-xl border border-[var(--ss-editor-border)] bg-[var(--ss-editor-header)] p-3"><div className="text-sm font-bold">{label(object)}</div><div className="mt-1 text-xs text-slate-500">{object.objectType === "CHARACTER" ? characterById.get(object.assetId)?.category ?? "Character" : propByAsset.get(object.assetId)?.category ?? "Prop"}</div></div></section>
              <section className="border-t border-[var(--ss-editor-border)] pt-4"><h3 className="text-[11px] font-bold uppercase tracking-[.14em] text-slate-500">Transform</h3><div className="mt-3 space-y-3"><label className="block text-xs font-semibold text-slate-400">X<input aria-label="X" type="number" value={Math.round(object.x)} onChange={e => updateObject(object.id, o => ({...o,x:clamp(Number(e.target.value)||0,0,1920)}))} className="mt-1.5 w-full rounded-lg border border-[var(--ss-editor-border-strong)] bg-[var(--ss-editor-header)] px-3 py-2 text-sm text-white outline-none focus:border-indigo-400 focus:ring-2 focus:ring-indigo-400/30"/></label><label className="block text-xs font-semibold text-slate-400">Y<input aria-label="Y" type="number" value={Math.round(object.y)} onChange={e => updateObject(object.id, o => ({...o,y:clamp(Number(e.target.value)||0,0,1080)}))} className="mt-1.5 w-full rounded-lg border border-[var(--ss-editor-border-strong)] bg-[var(--ss-editor-header)] px-3 py-2 text-sm text-white outline-none focus:border-indigo-400 focus:ring-2 focus:ring-indigo-400/30"/></label><label className="block text-xs font-semibold text-slate-400">Scale<input aria-label="Scale" type="number" step="0.05" min="0.25" max="3" value={object.scale} onChange={e => updateObject(object.id, o => ({...o,scale:clamp(Number(e.target.value)||1,0.25,3)}))} className="mt-1.5 w-full rounded-lg border border-[var(--ss-editor-border-strong)] bg-[var(--ss-editor-header)] px-3 py-2 text-sm text-white outline-none focus:border-indigo-400 focus:ring-2 focus:ring-indigo-400/30"/></label><div className="flex items-center justify-between rounded-lg border border-[var(--ss-editor-border)] bg-[var(--ss-editor-header)] px-3 py-2 text-xs"><span className="text-slate-400">Rotation</span><span className="font-semibold">{object.rotation}° · read-only</span></div></div></section>
              <section className="border-t border-[var(--ss-editor-border)] pt-4"><h3 className="text-[11px] font-bold uppercase tracking-[.14em] text-slate-500">Appearance</h3><div className="mt-3 space-y-3"><label className="flex items-center justify-between gap-3 rounded-lg border border-[var(--ss-editor-border)] bg-[var(--ss-editor-header)] px-3 py-2.5 text-xs font-semibold"><span>Visible</span><input type="checkbox" checked={object.visible} onChange={e => updateObject(object.id,o=>({...o,visible:e.target.checked}))} className="h-4 w-4 accent-indigo-500"/></label><Button variant="ghost" onClick={()=>updateObject(object.id,o=>({...o,x:960,y:540,scale:1,rotation:0}))} className="w-full border border-[var(--ss-editor-border-strong)] text-slate-200 hover:bg-white/10 hover:text-white">Reset transform</Button></div></section>
              <section className="border-t border-[var(--ss-editor-border)] pt-4"><h3 className="text-[11px] font-bold uppercase tracking-[.14em] text-slate-500">Layer</h3><div className="mt-3 grid grid-cols-2 gap-2"><Button variant="ghost" onClick={()=>moveLayer(\"back\")} className="border border-[var(--ss-editor-border-strong)] text-slate-200 hover:bg-white/10 hover:text-white">Send to Back</Button><Button variant="ghost" onClick={()=>moveLayer(\"front\")} className="border border-[var(--ss-editor-border-strong)] text-slate-200 hover:bg-white/10 hover:text-white">Bring to Front</Button><Button variant="ghost" onClick={()=>moveLayer(\"backward\")} className="border border-[var(--ss-editor-border-strong)] text-slate-200 hover:bg-white/10 hover:text-white">Send Backward</Button><Button variant="ghost" onClick={()=>moveLayer(\"forward\")} className="border border-[var(--ss-editor-border-strong)] text-slate-200 hover:bg-white/10 hover:text-white">Bring Forward</Button></div></section>
              <Button variant="danger" onClick={()=>{setComposition(c=>c?{...c,scenes:c.scenes.map(s=>({...s,objects:s.objects.filter(x=>x.id!==object.id)}))}:c);setSelected(null)}} className="w-full justify-center border-red-900/40 bg-red-950/20 text-red-300 hover:bg-red-950/40">Delete object</Button>
            </> : <div className="rounded-xl border border-dashed border-[var(--ss-editor-border-strong)] bg-[var(--ss-editor-header)] px-4 py-8 text-center"><div className="text-xs font-bold uppercase tracking-[.14em] text-slate-500">No selection</div><h3 className="mt-2 text-sm font-bold">Select something on the stage</h3><p className="mt-1 text-xs leading-5 text-slate-500">Select a character or prop on the stage to edit it.</p></div>}
            <section className="border-t border-[var(--ss-editor-border)] pt-4"><h3 className="text-[11px] font-bold uppercase tracking-[.14em] text-slate-500">Background</h3><div className="mt-3 rounded-lg border border-[var(--ss-editor-border)] bg-[var(--ss-editor-header)] px-3 py-2.5"><div className="text-xs font-semibold text-white">{backgroundName || "None"}</div><div className="mt-1 text-[10px] leading-4 text-slate-500">Controlled preset. Changes here affect Composition only.</div></div><div className="mt-2 space-y-1">{ctx.backgroundOptions.map(b=><button key={b.key} onClick={()=>updateScene(s=>({...s,background:{assetId:"background-preset:"+b.key}}))} aria-pressed={backgroundName===b.key} className={cx("flex w-full items-center justify-between rounded-lg border px-3 py-2 text-left text-xs transition focus:outline-none focus-visible:ring-2 focus-visible:ring-indigo-400",backgroundName===b.key?"border-indigo-400/60 bg-indigo-500/10 text-white":"border-[var(--ss-editor-border)] text-slate-400 hover:bg-white/5 hover:text-white")}><span>{b.name}</span><span className="text-[10px] text-slate-600">{b.category}</span></button>)}<button disabled={!backgroundName} onClick={()=>updateScene(s=>{const next={...s};delete next.background;return next})} className="mt-1 w-full rounded-lg px-3 py-2 text-left text-xs font-semibold text-red-300 hover:bg-red-950/20 disabled:opacity-30">Remove background</button></div></section>
          </div>
        </aside>
      </div>
    </main>
  );
}
