import { cloneElement, isValidElement, useId } from "react";
import type { ButtonHTMLAttributes, HTMLAttributes, InputHTMLAttributes, ReactElement, ReactNode, SelectHTMLAttributes, TextareaHTMLAttributes } from "react";

export const cx=(...v:Array<string|false|null|undefined>)=>v.filter(Boolean).join(" ");

export function BrandMark(){return <div className="flex items-center gap-2.5"><span className="grid h-9 w-9 place-items-center rounded-xl bg-indigo-600 text-sm font-black text-white shadow-sm">S</span><span className="text-[15px] font-semibold tracking-tight">StorySprout</span></div>}

export function StudioShell({children,className}: {children:ReactNode;className?:string}){return <div className={cx("min-h-screen bg-[var(--ss-bg)] text-[var(--ss-text)]",className)}>{children}</div>}

export function StudioHeader({backHref,backLabel,context,actions}: {backHref?:string;backLabel?:string;context?:ReactNode;actions?:ReactNode}){return <header className="sticky top-0 z-20 border-b border-[var(--ss-border)] bg-white/95 backdrop-blur-sm"><div className="mx-auto flex min-h-16 max-w-7xl items-center justify-between gap-4 px-5 lg:px-8"><div className="flex min-w-0 items-center gap-4">{backHref&&<a href={backHref} className="shrink-0 rounded-lg px-2 py-1.5 text-sm font-medium text-[var(--ss-muted)] hover:bg-slate-50 hover:text-[var(--ss-text)] focus:outline-none focus-visible:ring-2 focus-visible:ring-[var(--ss-primary)]">{backLabel??"Back"}</a>}<BrandMark/>{context&&<><span className="text-slate-300">/</span><div className="min-w-0 truncate text-sm font-medium">{context}</div></>}</div>{actions&&<div className="flex shrink-0 items-center gap-2">{actions}</div>}</div></header>}

export function PageIntro({eyebrow,title,description,actions}: {eyebrow?:string;title:string;description?:string;actions?:ReactNode}){return <div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><div className="mb-2 text-xs font-semibold uppercase tracking-[.16em] text-[var(--ss-primary)]">{eyebrow}</div><h1 className="text-3xl font-bold tracking-tight sm:text-4xl">{title}</h1>{description&&<p className="mt-2 max-w-2xl text-[15px] leading-6 text-[var(--ss-muted)]">{description}</p>}</div>{actions&&<div className="flex flex-wrap gap-2">{actions}</div>}</div>}

export function Button({variant="primary",className,...props}:ButtonHTMLAttributes<HTMLButtonElement>&{variant?: "primary"|"secondary"|"ghost"|"danger"|"ai"}){const styles={primary:"bg-[var(--ss-primary)] text-white hover:bg-[var(--ss-primary-strong)] shadow-sm",secondary:"border border-[var(--ss-border-strong)] bg-white text-[var(--ss-text)] hover:bg-slate-50",ghost:"bg-transparent text-[var(--ss-muted)] hover:bg-slate-100 hover:text-[var(--ss-text)]",danger:"border border-red-200 bg-white text-red-700 hover:bg-red-50",ai:"bg-violet-50 text-violet-700 ring-1 ring-inset ring-violet-200 hover:bg-violet-100"}[variant];return <button {...props} className={cx("inline-flex min-h-10 items-center justify-center rounded-[10px] px-4 py-2 text-sm font-semibold transition duration-150 focus:outline-none focus-visible:ring-2 focus-visible:ring-[var(--ss-primary)] disabled:cursor-not-allowed disabled:opacity-45",styles,className)}/>}

export function IconButton({className,...props}:ButtonHTMLAttributes<HTMLButtonElement>){return <button {...props} className={cx("inline-flex h-9 w-9 items-center justify-center rounded-lg border border-transparent text-slate-500 transition hover:bg-slate-100 hover:text-slate-900 focus:outline-none focus-visible:ring-2 focus-visible:ring-[var(--ss-primary)] disabled:opacity-40",className)}/>}

const field="w-full rounded-[10px] border border-[var(--ss-border-strong)] bg-white px-3.5 py-2.5 text-sm outline-none transition placeholder:text-slate-400 focus:border-[var(--ss-primary)] focus:ring-2 focus:ring-indigo-100";
export function Input(props:InputHTMLAttributes<HTMLInputElement>){return <input {...props} className={cx(field,props.className)}/>}
export function Textarea(props:TextareaHTMLAttributes<HTMLTextAreaElement>){return <textarea {...props} className={cx(field,"resize-y",props.className)}/>}
export function Select(props:SelectHTMLAttributes<HTMLSelectElement>){return <select {...props} className={cx(field,"bg-white",props.className)}/>}
export function Field({label,id,help,error,children}: {label:string;id?:string;help?:string;error?:string;children:ReactNode}){const generatedId=useId().replace(/:/g,"");const props=isValidElement(children)&&children.props&&typeof children.props==="object"?(children.props as Record<string,unknown>):null;const childId=props&&typeof props.id==="string"?props.id:undefined;const controlId=id??childId??("field-"+generatedId);const control=isValidElement(children)?cloneElement(children as ReactElement<{id?:string}>,{id:childId??controlId}):children;return <div><label htmlFor={controlId} className="text-sm font-semibold">{label}</label>{help&&<p id={controlId+"-help"} className="mt-1 text-xs text-[var(--ss-muted)]">{help}</p>}<div className="mt-2">{control}</div>{error&&<p id={controlId+"-error"} role="alert" className="mt-1.5 text-xs font-medium text-red-700">{error}</p>}</div>}

export function Panel({children,className}:HTMLAttributes<HTMLDivElement>){return <div className={cx("rounded-[16px] border border-[var(--ss-border)] bg-white shadow-[var(--ss-shadow-raised)]",className)}>{children}</div>}
export function Card({children,className}:HTMLAttributes<HTMLElement>){return <article className={cx("rounded-[16px] border border-[var(--ss-border)] bg-white shadow-[var(--ss-shadow-raised)]",className)}>{children}</article>}

export function EmptyState({icon,title,description,action}: {icon?:ReactNode;title:string;description?:string;action?:ReactNode}){return <div className="rounded-[18px] border border-dashed border-slate-300 bg-white px-6 py-16 text-center"><div className="mx-auto grid h-12 w-12 place-items-center rounded-2xl bg-slate-100 text-xl">{icon??"✦"}</div><h2 className="mt-4 text-lg font-bold">{title}</h2>{description&&<p className="mx-auto mt-2 max-w-md text-sm leading-6 text-[var(--ss-muted)]">{description}</p>}{action&&<div className="mt-6">{action}</div>}</div>}

export function Notice({tone="info",children}:{tone?:"info"|"success"|"error"|"ai";children:ReactNode}){const s={info:"border-indigo-100 bg-indigo-50 text-indigo-800",success:"border-emerald-100 bg-emerald-50 text-emerald-800",error:"border-red-100 bg-red-50 text-red-800",ai:"border-violet-100 bg-violet-50 text-violet-800"}[tone];return <div role={tone==="error"?"alert":"status"} className={cx("rounded-[12px] border px-4 py-3 text-sm",s)}>{children}</div>}

export function SaveState({state}:{state:"saved"|"unsaved"|"saving"|"error"|"conflict"}){const map={saved:["Saved","text-emerald-700 bg-emerald-50"],unsaved:["Unsaved changes","text-amber-700 bg-amber-50"],saving:["Saving…","text-slate-600 bg-slate-100"],error:["Save failed","text-red-700 bg-red-50"],conflict:["Conflict","text-red-700 bg-red-50"]} as const;const [label,style]=map[state];return <span aria-live="polite" className={cx("inline-flex items-center rounded-full px-2.5 py-1 text-xs font-semibold",style)}>{label}</span>}

export function AiBadge(){return <span className="inline-flex items-center gap-1 rounded-full bg-violet-50 px-2.5 py-1 text-[11px] font-semibold text-violet-700 ring-1 ring-inset ring-violet-100">✦ AI</span>}
