"use client";
import Link from "next/link";
import { useParams } from "next/navigation";
import { useEffect, useState } from "react";
import { ApiError, addCharacterToStory, Character, CharacterCategory, createCharacter, deleteCharacter, generateCharacter, getOutline, listProjectCharacters, listStoryCharacters, removeCharacterFromStory, updateCharacter } from "../../../../lib/api";
const cats:CharacterCategory[]=["CHILD","ADULT","ANIMAL","FANTASY","OBJECT","OTHER"];
const labels:Record<CharacterCategory,string>={CHILD:"Child",ADULT:"Adult",ANIMAL:"Animal",FANTASY:"Fantasy",OBJECT:"Object",OTHER:"Other"};
const icon:Record<CharacterCategory,string>={CHILD:"🧒",ADULT:"🧑",ANIMAL:"🐾",FANTASY:"✨",OBJECT:"🧸",OTHER:"⭐"};
type Draft={name:string;roleDescription:string;category:CharacterCategory;visualDescription:string;personality:string}; const blank:Draft={name:"",roleDescription:"",category:"CHILD",visualDescription:"",personality:""};
export default function Characters(){const {storyId}=useParams<{storyId:string}>();const[storyChars,setStoryChars]=useState<Character[]>([]),[library,setLibrary]=useState<Character[]>([]),[projectId,setProjectId]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[message,setMessage]=useState<string|null>(null),[draft,setDraft]=useState<Draft>(blank),[editing,setEditing]=useState<string|null>(null),[idea,setIdea]=useState(""),[busy,setBusy]=useState(false);
async function load(){setLoading(true);try{const outline=await getOutline(storyId);setProjectId(outline.story.projectId);const[sc,lib]=await Promise.all([listStoryCharacters(storyId),listProjectCharacters(outline.story.projectId)]);setStoryChars(sc);setLibrary(lib);}catch(e){setError(e instanceof ApiError?e.message:"We couldn't load Characters.");}finally{setLoading(false)}}useEffect(()=>{load()},[storyId]);
const used=new Set(storyChars.map(c=>c.id));const valid=!!draft.name.trim()&&draft.name.trim().length<=120&&!!draft.roleDescription.trim()&&draft.roleDescription.trim().length<=1000&&!!draft.visualDescription.trim()&&draft.visualDescription.trim().length<=2000&&draft.personality.trim().length<=1000;
async function save(){if(!valid||busy)return;setBusy(true);setMessage(null);try{if(editing)await updateCharacter(projectId,editing,draft);else{const c=await createCharacter(projectId,draft);await addCharacterToStory(storyId,c.id)}setDraft(blank);setEditing(null);await load()}catch(e){setMessage(e instanceof ApiError?e.message:"Couldn't save character.")}finally{setBusy(false)}}
async function generate(){if(!idea.trim()||busy)return;setBusy(true);setMessage(null);try{const s=await generateCharacter(projectId,{idea:idea.trim(),storyId});setDraft({name:s.name,roleDescription:s.roleDescription,category:s.category,visualDescription:s.visualDescription,personality:s.personality??""});setEditing(null)}catch(e){setMessage(e instanceof ApiError?e.message:"Character generation failed.")}finally{setBusy(false)}}
async function remove(c:Character){if(!confirm(`Remove ${c.name} from this story? The reusable character will remain in the Project.`))return;try{await removeCharacterFromStory(storyId,c.id);await load()}catch(e){setMessage(e instanceof ApiError?e.message:"Couldn't remove character.")}}
async function del(c:Character){if(used.has(c.id)){setMessage("Remove this character from its Stories before deleting the reusable Project character.");return}if(!confirm(`Delete ${c.name} from the Project library?`))return;try{await deleteCharacter(projectId,c.id);await load()}catch(e){setMessage(e instanceof ApiError?e.message:"Couldn't delete character.")}}
if(loading)return <main className="min-h-screen bg-slate-50 p-10"><div className="mx-auto max-w-6xl rounded-2xl bg-white p-8">Loading Characters…</div></main>;if(error)return <main className="p-10"><div role="alert">{error}</div></main>;
return <main className="min-h-screen bg-slate-50 text-slate-950"><div className="mx-auto max-w-6xl px-6 py-8"><Link href={`/stories/${storyId}/outline`} className="text-sm text-slate-500">← Story Outline</Link><header className="mt-5 flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-semibold text-indigo-600">CHARACTERS</p><h1 className="text-3xl font-bold">Build your story cast</h1><p className="mt-2 text-sm text-slate-600">Reusable Project characters can appear in multiple scenes and Stories.</p></div><Link href={`/stories/${storyId}/scene-setup`} className={`rounded-xl px-5 py-3 font-semibold ${storyChars.length?"bg-slate-950 text-white":"pointer-events-none bg-slate-200 text-slate-400"}`}>Continue to Scene Setup →</Link></header>{message&&<div role="alert" className="mt-5 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{message}</div>}
<section className="mt-8 grid gap-8 lg:grid-cols-[1fr_360px]"><div><h2 className="text-lg font-bold">Characters in this story</h2>{storyChars.length===0?<div className="mt-4 rounded-2xl border border-dashed bg-white p-10 text-center"><div className="text-4xl">🌱</div><p className="mt-3 font-semibold">No characters yet</p><p className="mt-1 text-sm text-slate-500">Create one or add a reusable character below.</p></div>:<div className="mt-4 grid gap-4 md:grid-cols-2">{storyChars.map(c=><Card key={c.id} c={c} edit={()=>{setEditing(c.id);setDraft({name:c.name,roleDescription:c.roleDescription,category:c.category,visualDescription:c.visualDescription,personality:c.personality??""})}} remove={()=>remove(c)} del={()=>del(c)}/>)}</div>}<h2 className="mt-10 text-lg font-bold">Project character library</h2><p className="text-sm text-slate-500">Reusable characters for this Project.</p><div className="mt-4 grid gap-4 md:grid-cols-2">{library.filter(c=>!used.has(c.id)).map(c=><Card key={c.id} c={c} add={async()=>{await addCharacterToStory(storyId,c.id);await load()}} edit={()=>{setEditing(c.id);setDraft({name:c.name,roleDescription:c.roleDescription,category:c.category,visualDescription:c.visualDescription,personality:c.personality??""})}} del={()=>del(c)}/>)}</div></div>
<aside className="h-fit rounded-2xl bg-white p-5 shadow-sm"><h2 className="font-bold">{editing?"Edit Character":"Create Character"}</h2><p className="mt-1 text-xs text-slate-500">Edits affect every Story using this reusable character.</p><Field label="Name" value={draft.name} set={v=>setDraft({...draft,name:v})}/><Field label="Role description" value={draft.roleDescription} set={v=>setDraft({...draft,roleDescription:v})} area/><label className="mt-3 block text-sm font-semibold">Category<select value={draft.category} onChange={e=>setDraft({...draft,category:e.target.value as CharacterCategory})} className="mt-1 w-full rounded-lg border p-2">{cats.map(c=><option key={c}>{c}</option>)}</select></label><Field label="Visual description" value={draft.visualDescription} set={v=>setDraft({...draft,visualDescription:v})} area/><Field label="Personality (optional)" value={draft.personality} set={v=>setDraft({...draft,personality:v})} area/><button disabled={!valid||busy} onClick={save} className="mt-4 w-full rounded-xl bg-slate-950 p-3 text-sm font-semibold text-white disabled:opacity-40">{busy?"Working…":editing?"Save Character":"Create & Add to Story"}</button>{editing&&<button onClick={()=>{setEditing(null);setDraft(blank)}} className="mt-2 w-full rounded-xl border p-3 text-sm font-semibold">Cancel</button>}<hr className="my-6"/><h3 className="font-bold">Generate with AI</h3><p className="mt-1 text-xs text-slate-500">Suggestion only — nothing is saved until you create it.</p><textarea value={idea} onChange={e=>setIdea(e.target.value)} rows={3} placeholder="A brave little fox who loves helping friends…" className="mt-3 w-full rounded-lg border p-3 text-sm"/><button disabled={!idea.trim()||busy} onClick={generate} className="mt-2 w-full rounded-xl border border-indigo-200 bg-indigo-50 p-3 text-sm font-semibold text-indigo-700 disabled:opacity-40">Generate Suggestion</button><p className="mt-4 text-xs text-slate-500">V1 visual: deterministic placeholder/avatar. No image generation or upload.</p></aside></section></div></main>}
function Field({label,value,set,area=false}:{label:string;value:string;set:(v:string)=>void;area?:boolean}){return <label className="mt-3 block text-sm font-semibold">{label}{area?<textarea value={value} onChange={e=>set(e.target.value)} rows={3} className="mt-1 w-full rounded-lg border p-2"/>:<input value={value} onChange={e=>set(e.target.value)} className="mt-1 w-full rounded-lg border p-2"/>}</label>}
function Card({c,edit,remove,add,del}:{c:Character;edit:()=>void;remove?:()=>void;add?:()=>void;del:()=>void}){return <article className="rounded-2xl border bg-white p-5"><div className="flex gap-4"><div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-slate-100 text-2xl" aria-label="Placeholder avatar">{icon[c.category]}</div><div><h3 className="font-bold">{c.name}</h3><p className="text-xs font-semibold text-indigo-600">{labels[c.category]}</p><p className="mt-2 text-sm text-slate-600">{c.roleDescription}</p></div></div><p className="mt-3 text-xs text-slate-500">{c.visualDescription}</p><div className="mt-4 flex flex-wrap gap-2">{add&&<button onClick={add} className="rounded-lg bg-slate-950 px-3 py-2 text-xs font-semibold text-white">Add to Story</button>}<button onClick={edit} className="rounded-lg border px-3 py-2 text-xs font-semibold">Edit</button>{remove&&<button onClick={remove} className="rounded-lg border px-3 py-2 text-xs">Remove</button>}<button onClick={del} className="rounded-lg border border-red-200 px-3 py-2 text-xs text-red-600">Delete</button></div></article>}
